### ISSUE TITLE
[Chore] - setup nx cache

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#1005]
Bumbed Lerna to v7, which allows us to use NX by simply optin to `"useNx": true,`.

For now I only setup nx cache for the lerna build. That way locally when we build it only builds updated packages :) Way faster than before:

![Image](https://github.com/adevinta/spark/assets/2033710/f8a2f580-6401-49b0-a24e-eebc18c81351)

**Comment by acd02** [comment]
I think we can close this issue, right? cc @Powerplex

**Comment by soykje** [comment]
There is no opened PR there, is it?
