### ISSUE TITLE
[Text Area] Resolve the "clear-button" discussion

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1149]

**Comment by JeremiasUX** [comment]
Decision has been made here: https://adevinta.slack.com/archives/C05B0MH7XRC/p1689686106025889

Decision:
- No clear button for the TextArea
- Trailing element still possible

Next steps:
- Update Figma and ZeroHeight documentation. 
- Ticket: [[Documentation] TextArea: Remove the closing indicator from guidelines#1296](https://github.com/adevinta/spark/issues/1296)
