### ISSUE TITLE
[form field] Document the FormField in isolation

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1173]
As discussed in the conversation on [Feb 7th ](https://adevinta.enterprise.slack.com/archives/C04LNCEMMUN/p1707301172105629)we will document FormFIel for iOS in isolation from the Checkboxes, Inputs, etc

Please do include Max Char in the specs [this thread](https://adevinta.slack.com/archives/C04QQEU3Y2H/p1689944343083939) too

**Comment by JeremiasUX** [comment]
Done and spec is available and currently iterated
