### ISSUE TITLE
[colours] Update all Spark components after the colours refactor

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1174]

**Comment by Bibisirius** [comment]
Update Colour :
- [ ] ICheckbox (in progress)
- [ ] Radio button
- [ ] Switch
- [ ] Button
- [ ] Icon button
- [ ] Tag
- [ ] Badge
- [ ] Input color
- [ ] Popover
- [ ] Text-view area

Zeroheight guideline color:
- [ ]  Checkbox 
- [ ] Radio button 
- [ ] Switch 
- [ ] Button 
- [ ] Icon button 
- [ ] Tag
- [ ] Badge

**Comment by JeremiasUX** [comment]
- [ ] Chips
- [ ] Dropdown
- [ ] Label
