### ISSUE TITLE
[Input] Check the ZeroHeight documentation agains our agreements

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1175]
- [ ] Check this thread: https://adevinta.slack.com/archives/C054Q84KPJ4/p1689690867363129
- [ ] And the storybook: https://sparkui.vercel.app/?path=/docs/components-input--docs
- [ ] And the Android implementation

**Comment by JeremiasUX** [comment]
We are working on the improvement of the input spec right now. This will ensure everything is documented
