### ISSUE TITLE
[Tokens] Add missing icons

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1187]
**Lists of icons to be migrated :** (to be verified)

- [others/megaphone-mute](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?type=design&node-id=316-8102&mode=design&t=BE23cb3md4uNrufR-11)
- [images/error-photo](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?type=design&node-id=316-8102&mode=design&t=BE23cb3md4uNrufR-11)
- [criteria/vehicles/car-brand](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?type=design&node-id=316-8102&mode=design&t=BE23cb3md4uNrufR-11)
- [criteria/mode/clothes-brand](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?type=design&node-id=316-8102&mode=design&t=BE23cb3md4uNrufR-11)
- [criteria/mode/luxe](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?type=design&node-id=316-8102&mode=design&t=BE23cb3md4uNrufR-11)
- [criteria/vehicles/car-type](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?type=design&node-id=316-8102&mode=design&t=BE23cb3md4uNrufR-11)

Thanks

**Comment by Bibisirius** [comment]
I'll add a few more that are missing from the list:

- [criteria/new-estate/parking-estate](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?type=design&node-id=1508-5074&mode=design&t=QEV5LkYcdx359UyU-4)
- [criteria/job/job-type](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?type=design&node-id=1508-5122&mode=design&t=QEV5LkYcdx359UyU-4)
- [criteria/mode/clothes-condition](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?type=design&node-id=1508-5032&mode=design&t=QEV5LkYcdx359UyU-4)
- [criteria/rent/common](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?type=design&node-id=1508-5060&mode=design&t=QEV5LkYcdx359UyU-4)

**Comment by solygambas** [comment]
Closed by [59](https://github.com/adevinta/spark-tokens/pull/59)

**Comment by Bibisirius** [comment]
We forgot the avatar, which is not available

**Comment by solygambas** [comment]
No problem, please create another ticket for next sprint :)
