### ISSUE TITLE
[All components] Check and improve the current focus styles

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1197]
Task:
Let's try this one
`box-shadow: 0 0 0 2px var(background), 0 0 0 4px blue;`

The conversation started in [this thread in slack](https://adevinta.slack.com/archives/C03T2TXH64T/p1688993610303299) by @poweplex

> _There are also 2 things we can adjust for better focus styles:
inset/outset? now it seems to depend on the component's figma, sometimes it is one or the other. (Note: we think Inset looks nice + it won't be cropped in some cases) outline offset => In addition to the outline and its color, it could have an offset, itself with color.
Less pretty that's for sure :smile: But always provides contrast for readability
I'm referring to [this](https://www.w3.org/WAI/WCAG21/Techniques/css/C40)_

> More context in this other thread:
https://adevinta.slack.com/archives/C03T2TXH64T/p1694448070014139

**Comment by acd02** [comment]
PR (#1445) for this issue was merged 👍
