### ISSUE TITLE
Onboard Ahmed

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1223]
- [x] Slack channels
- [x] Github (check access, GAs, pluggins, bots)
- [x] Present Spark Android project
- [x] Contributing guidelines
- [x] Push a test PR to Spark repo
- [x] Releasing process
- [x] Design documents
- [x] Integration in Polaris
- [x] Spark Component Guideline

**Comment by MarinaRomanova** [comment]
draft of onboarding document - https://soulcramer.notion.site/Spark-Component-Guideline-4432b0fe3bc7410daa14a0aec9e31933?pvs=4
