### ISSUE TITLE
[ZeroHeight] Update the Foundations' documentation after the refactor of colours

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1224]
ZeroHeight: https://spark.adevinta.com/1186e1705/p/0879a9-colors/b/27d7a3

- Add 2 tokens: Accent and Basic
- Rename primary color to `main`, and secondary color to `support`
- Document very well and detailed how to use DIMs

----
FYI, we received many requests like this one by Tega
> _ Are there any guidelines on how to use the "Dim" colours? I'm asking because I'm unsure about when to use 100% colour for text VS when to use 72% colour (Dim 1 - Text) or 56% colour (Dim 2 - Icon). Also, some of these dim colours don't seem to be accessible so I'm curious to know if there is a guide_

**Comment by ChrisDesignOps** [comment]
Colors updated on [ZH specs](https://spark.adevinta.com/1186e1705/p/0879a9-colors) & [Figma Playground](https://www.figma.com/file/WCMIsZFXpUzkapA00Qjnql/Color-System---Playground?type=design&node-id=0%3A1&mode=design&t=qI6Z9RmtFuX6E8W8-1):

1. Rename & update colors styles
2. Added Support & Basic description (⚠️ important to review)
3. Added Background vs Surface explanation
4. Added Dim detailed explanation 
5. Added multi theme visual example (Spark vs LBC vs KA)
6. Added Dos Donts with the semantic language example
7. Improving playground exercises examples (wip)
