### ISSUE TITLE
[Zeroheight] Add documentation for Spark Tokens for Figma

### ISSUE THREAD

**Issue by solygambas** [adevinta/spark#1225]

**Comment by solygambas** [comment]
https://zeroheight.com/836b236c5/v/latest/p/394707-spark-tokens-for-figma

**Comment by solygambas** [comment]
add screenshots and videos?

**Comment by turolopezsanabria** [comment]
Screenshots would be awesome.
You can close the task afterwards, and c reate a new one for the Videos
