### ISSUE TITLE
[UI Kits] Why do we have Brand Colours hardcoded as styles in the UI Kits?

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1241]
# Task
Unpublish Brand colours

## Background
If we don't allow teams to use these colors, but the semantic palette:
Why do we expose them in the libraries?

![Image](https://github.com/adevinta/spark/assets/23620759/4690a412-6232-4b83-a148-5ab5cf3347d4)

**Comment by ChrisDesignOps** [comment]
[Figma branch to review](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/branch/WwuGzVEAPkkXPbUqy6PCLc/Spark-Foundations?type=design&mode=design&t=N4SpZb2535oGQRfF-1)

**Comment by JeremiasUX** [comment]
Looks good to me. I will create sub-tasks to unpublish the brand colors for other Brand-Foundations as well

**Comment by JeremiasUX** [comment]
Sub-task:

- [#2094](https://github.com/adevinta/spark/issues/2094): remove from EU5 brands as well
