### ISSUE TITLE
[Zeroheight] Update all Spark components documentations after the color refactor

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#1245]
```[tasklist]
### Zeroheight guidelines color update:
- [x] Checkbox
- [x] Radio Button
- [x] Switch
- [x] Tab
- [x] Spinner
```

**Comment by lauragautheron** [comment]
should we add the documentation for the colors as well or is it part of another ticket ?

**Comment by JeremiasUX** [comment]
I think the task will be covered by this ticket: [[ZeroHeight] Update the Foundations' documentation after the refactor of colours#1224](https://github.com/adevinta/spark/issues/1224)

**Comment by JeremiasUX** [comment]
I don't think so.

Do you mean the figma documentation is not up to date?

**Comment by lauragautheron** [comment]
Yes that's what I saw

**Comment by JeremiasUX** [comment]
Okay, I didn't created a ticket for this task

**Comment by lauragautheron** [comment]
ok I just did but it's not priorised, can I check the radio button update if you don't see any pblm with it ?

**Comment by JeremiasUX** [comment]
yes, feel free to check the radio button and close the ticket
