### ISSUE TITLE
[badge] Stroke and size fixes in: ZeroHeight, Figma, and Web

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1253]
See the complete conversation here:
https://adevinta.slack.com/archives/C03FVU53XU5/p1691584968126769

To complete this ticket: I added [the topic ](https://adevinta.slack.com/archives/C03FVU53XU5/p1691685864051829)of the size of the "no count" to change it to 8px rather than 12 px

## Task

Change small size no count to 8px

```[tasklist]
### To do
- [x] Adjust Figma
- [x] Adjust specs
- [x] Adjust Web react component
- [x] Adjust ZeroHeight
```

**Comment by Bibisirius** [comment]
To complete this ticket: I add the topic of the size of the "no count" to change it to 8px rather than 12 px

**Comment by Bibisirius** [comment]
The "no count" version has been changed to 8px 👍

**Comment by Bibisirius** [comment]
Ready ✅
