### ISSUE TITLE
[Components] - Button - loading button loses focus

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#1256]
When clicking or pressing Enter on a button, if it goes into "loading" mode, it loses the focus because we set it as `disabled`.

We have seen other design system use:
- `aria-disabled` instead of the `disabled` HTML attribute
- `aria-busy="true"` 

We should figure which is best and implement it.

For now, the focus goes back to the top of the page, which breaks the user flow when navigating with the keyboard.

![image](https://github.com/adevinta/spark/assets/66770550/984f8ca3-1267-4760-ac43-05de9daaaa48)

**Comment by soykje** [comment]
Seems clearer to use `aria-disabled` here. Also we may be interested in having a shared/common solution for all Spark components that could be disabled :+1:
