### ISSUE TITLE
[Tokens] The units of measurement on spacings are not the same on f zeroheights specs vs code

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#1259]
We have differences between the units of measurement for spacings on figma vs specs.

**Which is the correct version?**

**Code:**

![Image](https://user-images.githubusercontent.com/139967199/259806565-e31b5dd0-ce5d-4eda-bf1f-2c3aab26fd3e.png)

**Zeroheight:**

![Image](https://user-images.githubusercontent.com/139967199/259806916-704d1c60-5431-49d2-b2bf-2beac1ad8e53.png)

**Comment by turolopezsanabria** [comment]
Please check this one with Developers

**Comment by turolopezsanabria** [comment]
ZeroHeight is OK now.
We removed the mention to `REM` values, and left only the `token = size` pair

❌ md 1rem 8px
✅ md ~1rem~ 8px
