### ISSUE TITLE
List possible solutions to sync tokens between designers and our three platforms

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#126]

**Comment by solygambas** [comment]
- [Tokens Studio for Figma](https://www.figma.com/community/plugin/843461159747178978) [git repo](Tokens studio git https://github.com/tokens-studio/figma-plugin) + [style dictionary](https://amzn.github.io/style-dictionary/#/) [git repo](https://github.com/amzn/style-dictionary)
- [variables plugin](https://www.figma.com/community/plugin/1000963812142874727/variables)

- [Tuto 1](https://www.michaelmang.dev/blog/exporting-design-tokens-from-figma-with-style-dictionary)
- [Tuto 2](https://medium.com/@sarahkimirettig/push-design-tokens-to-developers-using-figma-tokens-plugin-and-style-dictionary-cli-build-tool-87c8aabd887b)
- [Backlight example](https://backlight.dev/docs/design-tokens-using-sd-figma)
