### ISSUE TITLE
[Design Specs] Drawer

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1262]
- [x] Figma spec : [url](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=11237-18027&mode=design&t=KYynl9KGrCjwLpmq-11)
- [x] [ZH spec ](https://zeroheight.com/1186e1705/v/latest/p/900abd-drawer/b/083ca4) To refine : Add 2 actions on the header 
- [x] Component: [url](https://www.figma.com/file/NsGfE3UnbhEyAPpVf3B60P/branch/o5UG7mmKHLQtuB9VUZehNf/Spark-Components?type=design&node-id=8936-22477&mode=design&t=hJJzPrTXLFx9cIlh-11) > Review

IOS and AND not applicable

**Comment by Bibisirius** [comment]
I'm waiting for the designers' opinions before making a decision on the component style.

Version 1: Complete component as dialog
Version 2: Simple component without overlay

**Comment by Bibisirius** [comment]
Waiting review design 

- [x] Version 2 : Simple component without ouverlay (waiting to test)
- [ ] To refine: Possibility to have 2 actions on the header (return button and close button)
- [ ] No for the logo, we can have it directly on Polaris
