### ISSUE TITLE
[Textfield] For error case : Specify that when an error occurs, the helper text is replaced by the error text.

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#1274]

**Comment by Bibisirius** [comment]
Specify that when an error occurs, the helper text is replaced by the error text. If there are legal notices, then specify that they should be added outside the input.

**Comment by JeremiasUX** [comment]
Should be part of the UX-Guideline for the Input. I'll close this ticket for now, we create a new one if needed.
