### ISSUE TITLE
Add a visual testing step in quality.yml (Chromatic)

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#128]

**Comment by solygambas** [comment]
- [x] Request access to Adevinta for Chromatic OAuth
- [] Add a visual testing step in [quality.yml](https://github.com/adevinta/spark/blob/main/.github/workflows/quality.yml)

Documentation:
[Previous setup](https://github.com/solygambas/react-projects/blob/main/.github/workflows/design-system.yml)
