### ISSUE TITLE
[Design Component] Update the default state for components

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#1280]
With the recent color changes, we need to do the following:

- [ ] Identify the components that should use "basic" as the default color
- [ ] Change the default state (if a user adds a new component it should use the basic color)
- [ ] Find a good solution to update all existing components (automatically)
- [ ] Communicate the change via a slack channel

**Comment by JeremiasUX** [comment]
- [ ] Chip
- [ ] Radio Button
- [ ] Checkbox
- [ ] Toggle
- [ ] Tabs
- [ ] Tag

**Comment by Bibisirius** [comment]
Tag : If you change the default colour, many mock-ups will be affected. What can you do? (cc @JeremiasUX @lauragautheron )

**Comment by Bibisirius** [comment]
Tag: We can change the colour but everyone should be warned not to update unless it's polaris components.
Same for the tabs

**Comment by lauragautheron** [comment]
I don't understand sorry : if the component changes in production, is it a problem if it changes everywhere ?

**Comment by Bibisirius** [comment]
@lauragautheron If we change the component, all the tag with main (primary) colour will become 'accent' (purple) like the tag 'à la une', 'nouveau', 'profil recommendé' ,etc....

We'll be saddling designers with an additional debt, as they'll have to redo everything manually.

**Comment by JeremiasUX** [comment]
Tag will be solved in this issue: [[Tag] Resolve the color issues#1310](https://github.com/adevinta/spark/issues/1310)
