### ISSUE TITLE
[Polaris] - Theme switcher on local and testing envs

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#1285]
- Implemented a `PolarisThemeSelector` on Polaris, only visible in local and test envs, to easility switch between brands themes.
- Implement a `PolarisThemeProvider` and its `useTheme` hook, which allows developers to switch the global theme of the app by calling `setTheme(myTheme)`

Test link: https://spark-theme-switched.next.ariane.leboncoin.ci/

=> Check the button to the bottom right of the screen.

**Comment by thomas-leguellec** [comment]
Topic took by a global taskforce which will manage all the i18n and not only DesignSystem
