### ISSUE TITLE
ZH: Update links to finished Android components

### ISSUE THREAD

**Issue by MarinaRomanova** [adevinta/spark#1309]
We have some links missing in Spark zeroheight to Android documentation for finished components:
Badge [github](https://github.com/adevinta/spark-android/tree/main/spark/src/main/kotlin/com/adevinta/spark/components/badge) and [dokka](https://adevinta.github.io/spark-android/spark/com.adevinta.spark.components.badge/index.html)
checkboxes, radios and switches [github](https://github.com/adevinta/spark-android/tree/main/spark/src/main/kotlin/com/adevinta/spark/components/toggles) and [dokka](https://adevinta.github.io/spark-android/spark/com.adevinta.spark.components.toggles/index.html)
Chip [github](https://github.com/adevinta/spark-android/tree/main/spark/src/main/kotlin/com/adevinta/spark/components/chips) and [dokka](https://adevinta.github.io/spark-android/spark/com.adevinta.spark.components.chips/index.html)
Icon [dokka](https://adevinta.github.io/spark-android/spark/com.adevinta.spark.components.icons/index.html) and [github](https://github.com/adevinta/spark-android/tree/main/spark/src/main/kotlin/com/adevinta/spark/components/icons)
Input/Textfield [github](https://github.com/adevinta/spark-android/tree/main/spark/src/main/kotlin/com/adevinta/spark/components/textfields) and [dokka](https://adevinta.github.io/spark-android/spark/com.adevinta.spark.components.textfields/index.html)
Modal is experimental [dokka](https://adevinta.github.io/spark-android/spark/com.adevinta.spark.components.dialog/-modal-full-screen-scaffold.html?query=fun%20ModalFullScreenScaffold(onClose:%20()%20-%3E%20Unit,%20modifier:%20Modifier%20=%20Modifier,%20snackbarHost:%20()%20-%3E%20Unit%20=%20{},%20illustration:%20Int?%20=%20null,%20mainButton:%20(Modifier)%20-%3E%20Unit%20=%20{},%20supportButton:%20(Modifier)%20-%3E%20Unit%20=%20{},%20reverseButtonOrder:%20Boolean%20=%20false,%20illustrationContentScale:%20ContentScale%20=%20ContentScale.Fit,%20content:%20(PaddingValues)%20-%3E%20Unit)) and [github](https://github.com/adevinta/spark-android/blob/main/spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalFullScreenScaffold.kt)
Spinner [github](https://github.com/adevinta/spark-android/tree/main/spark/src/main/kotlin/com/adevinta/spark/components/progress) and [dokka](https://adevinta.github.io/spark-android/spark/com.adevinta.spark.components.progress/index.html)
Tabs [github](https://github.com/adevinta/spark-android/tree/main/spark/src/main/kotlin/com/adevinta/spark/components/tab) and [dokka](https://adevinta.github.io/spark-android/spark/com.adevinta.spark.components.tab/index.html)
Tag [github](https://github.com/adevinta/spark-android/tree/main/spark/src/main/kotlin/com/adevinta/spark/components/tags) and dokka link is missing an image

<img width="713" alt="Screenshot 2023-08-24 at 09 54 42" src="https://github.com/adevinta/spark/assets/36896406/65f66675-6075-4c3b-9da1-399a47b12872">

**Comment by JeremiasUX** [comment]
Done
