### ISSUE TITLE
[Tokens] Update colour light leboncoin

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#1329]
**Some colours were no longer accessible**

**Impact:**

- Support container:  E6F2FD (Blueberry 100)
- On Support Container: 152233 (Blueberry 900)
- Support: 094171 (Blueberry 800)
- Support Variant: #0C5291 (Blueberry 700)
- -  Support hover: #0C5291

- Basic: #094171 (Blueberry 800)
- Basic container : #E6F2FD (Blueberry 100)
- On Basic Container: #152233 (Blueberry 500)
- Basic hover: #0C5291

**Base:** 
- On background / Variant/ On surface: #152233
- Surface Inverse: #2B3441
- Outline: #ACB8C7 (Nightshade 400) 
- Outline high:  #202730
- Overlay: #202730 (72% opacity) 

**Feedback:**
- Neutral Container: #F0F2F5 (Nightshade 100)
- On neutral container : #3A4757 (Nightshade 700)
- Info: #C2E0FA (Blueberry 200)
- On Info container : #0C5291 (Blueberry 700)

Bonus :
- Twitter: #14171A

**Comment by acd02** [comment]
it can be closed as the theme has been updated on LBC 👍
