### ISSUE TITLE
[Components] - Dialog - QA checks

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#1363]
Dialog component is aligned with spec for QA and design review: 

- Component is here: https://sparkui.vercel.app/?path=/docs/experimental-dialog--docs
- Spec: https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=7297-859&mode=design&t=eubFZb5eefccljnF-0

**Comment by elisa-hery** [comment]
The design part will be handled in https://github.com/adevinta/spark/issues/777, I close the ticket
