### ISSUE TITLE
[Github actions] - Cleanup storybook deployment

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#1369]
We noticed that every instance of Storybook is never destroyed after a branch is merged. 

For example, this PR from February, still has a live storybook instance deployed and running: https://spark-f4gjlgow5-spark-team.vercel.app/?path=/docs/build-build--docs

This is not very eco-friendly ^^

**Comment by andresin87** [comment]
https://vercel.com/docs/limits/fair-use-guidelines

**Comment by acd02** [comment]
@andresin87 , I'm not sure where you set the three-month threshold.
You mentioned this morning that any dynamic environment older than three months should be deleted, but this doesn't seem to be the case 😅 . See this example ➡️ https://github.com/adevinta/spark/pull/1033 (july 2023, ~6 month ago)

**Comment by andresin87** [comment]
Omg. Ill check. Thats 3m github deployment environments but this is in vercel so i need to review that part
