### ISSUE TITLE
[Components] Avoid animating overlay dialog when size is fullscreen

### ISSUE THREAD

**Issue by acd02** [adevinta/spark#1374]
When the size of the overlay dialog is set to fullscreen, the animation out effect should be avoided

**Comment by acd02** [comment]
> [!NOTE]  
After discussing with @Powerplex and @soykje ,we have decided to put this PR on hold for now.
> We may discard this pull request and instead refactor the Dialog component to use React Context.
> This will allow us to handle the bug without resorting to the escape hatch used in the current PR (adding a class to the body)

**Comment by elisa-hery** [comment]
Another PR was opened by @Powerplex, same goal but different approach --> https://github.com/adevinta/spark/pull/1410 
@Powerplex 's PR is tested & validated ✅

**Comment by acd02** [comment]
Yes, closing in favor of #1410 👍
