### ISSUE TITLE
[Component] add "info" intent for button

### ISSUE THREAD

**Issue by elisa-hery** [adevinta/spark#1377]
On iOS demo app, intent "info" is missing for `button`/`iconButton` component

<img src="https://user-images.githubusercontent.com/142396647/265024377-dcf5c98b-9c25-4f4a-b5fb-79daa6325a0a.png" alt="drawing" width="200"/>

**Comment by LouisBorleeAdevinta** [comment]
Testable on branch feature/button_add_info_intent
