### ISSUE TITLE
[Update specs] Update colors on Button's UI kit

### ISSUE THREAD

**Issue by elisa-hery** [adevinta/spark#1404]
On Button's UI kit : 
- for `Info` intent, color of the text is `onError` instead of `onInfo` 
- for `Basic` intents color of the text is `onError` instead of `onBasic`

<img src="https://user-images.githubusercontent.com/142396647/266021190-ec9aad13-0f0a-48a6-ad89-7c9a1cd964c3.png" alt="bug-info" width="300"/>

<img src="https://user-images.githubusercontent.com/142396647/266021514-fb17836e-4747-4a1b-a9b6-444bf9db743d.png" alt="bug-basic" width="300"/>

**Comment by JeremiasUX** [comment]
Icon color still uses "variables" -> needs to be fixed
