### ISSUE TITLE
[Fix] Button: remove small size from demo app

### ISSUE THREAD

**Issue by elisa-hery** [adevinta/spark#1407]
For now on iOS, buttons can have 3 sizes : small, medium, large. 
According to [the specs](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=2340%3A22556&mode=design&t=UNxhKmbozzWikW1y-1), **small size should only be used on web so it should be removed**. 

<img src="https://user-images.githubusercontent.com/142396647/266256769-c7f93e39-2907-4ecd-84ba-c0bb77d61448.png" alt="button-small" width="150"/>

**Comment by thomas-leguellec** [comment]
Need to check if the small size is used on Polaris side. If not we can delete it.
