### ISSUE TITLE
[Design Specs] Alert Dialog

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#1434]
- [x] [Component on Figma](https://www.figma.com/file/NsGfE3UnbhEyAPpVf3B60P/branch/h1tOG2nB9y1GUm15RlvL7v/Spark-Components?type=design&node-id=8663-19009&mode=design&t=RsD4T5fV68JRLHB5-11)
- [x] Review and test
- [x] [ZeroHeight Documentation](https://zeroheight.com/1186e1705/v/latest/p/991cc1-alert-dialog/b/02a6bc)
- [x] Merge

**Comment by Bibisirius** [comment]
**Adjust the placeholder in 2 versions:**
- With padding
- Without padding

**Comment by turolopezsanabria** [comment]
please @turolopezsanabria @JeremiasUX check this one so we can close it
