### ISSUE TITLE
Update the FOCUS styles in ZeroHeight & figma

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1447]
Based on this conversation and [this PR](https://github.com/adevinta/spark/pull/1445), and [this conversation](https://adevinta.slack.com/archives/C04LNCEMMUN/p1694595990644679)

Figma: Effekt -> Focus style

Compare [Storybook](https://sparkui.vercel.app/?path=/docs/getting-started--docs) with [Figma](https://www.figma.com/design/NsGfE3UnbhEyAPpVf3B60P/Spark-Components?node-id=0-1&t=C1AyB6F39f9VinEu-0).

`box-shadow: 0 0 0 2px rgb(var(--colors-background)), 0 0 0 4px blue;`

`box-shadow: 0 0 0 0 rgb(var(--colors-background)) inset, 0 0 0 2px blue inset;`

- [x] button
- [x] checkbox
- [x] chips
- [x] iconButton
- [x] TextLink 
- [x] RadioButton
- [x] Switch
- [x] Tabs

**Comment by JeremiasUX** [comment]
Brand foundations need to be updated as well (Figma and ZH)

**Comment by Bibisirius** [comment]
Approved and ready for publication ✅

**Comment by Bibisirius** [comment]
Done ✅
