### ISSUE TITLE
[Component Figma] Update the label & Switch icon size

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1454]
Update the label in Switch based in [this feedback](https://adevinta.slack.com/archives/C054A58L2G1/p1694176110244769?thread_ts=1694163424.503789&cid=C054A58L2G1)
![Image](https://user-images.githubusercontent.com/23620759/268392622-342e5e21-4746-437b-a0b8-7d52c23072c6.png)

-----

Issue has been reported here: https://adevinta.slack.com/archives/C059UCP6B63/p1710503284684049

**Summary:**

- The switch with label size does not adapt by changing medium-size to small-size
-  Investigate the issue
-  Fix the issue
-  Communicate the fix

-----
**We discovered that we have incorrect icon sizes in our switch component.**

![Image](https://github.com/user-attachments/assets/8df4537a-0ad7-45bc-bf5d-2188969c3fd1)

- In [Web](https://sparkui.vercel.app/?path=/docs/components-switch--docs#sizes) we have 12px for the larger size and 10px for the smallest.
- AS seen we should make them all 12px (image)

![Image](https://github.com/user-attachments/assets/ff54ec15-3ee7-400c-8f63-0c01ff424b99)

**Whats needs to be done?**

- Sync the icon size for all platforms
- If needed update icons -> Figma needs to be updated

**Comment by Bibisirius** [comment]
### After investigation, the size is right ✅ 

**Web:**
We have the default sizes small and medium

**Android:**
The icon size is smaller on the default small version. 

**iOS:** 
We have the default size small and medium

----

To explore the possibility to have 1 title & 1 subtitle for switch or suggest doing it directly in the Keyscreens

**Comment by Bibisirius** [comment]
This case is mainly used on Depot. It remains to be seen whether it can be customised directly in the product using the switch + custom label. To be confirmed
