### ISSUE TITLE
Clarify specs for Checkbox, Radio and Switch components

### ISSUE THREAD

**Issue by lauragautheron** [adevinta/spark#1464]
Following the message of @michael-zimmermann [here](https://adevinta.slack.com/archives/C053L5Q8WBH/p1695030705543799) we realised 

- a difference between specs in figma and zeroheight of the checkbox
- a difference between what has been specified for checkboxes and radio buttons and switches

this task's goal is to understand why and to unify the specs

**Comment by lauragautheron** [comment]
list of differences here : https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=10014%3A24385&mode=design&t=dXwli0bltLrZhwtn-1

**Comment by JeremiasUX** [comment]
Specs have been updated
