### ISSUE TITLE
[Components] - Dialog - release stable

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#1472]
https://spark-porypcvnv-spark-team.vercel.app/?path=/docs/components-dialog--docs

**Comment by elisa-hery** [comment]
@Bibisirius component available for design review ! (see link above)

**Comment by elisa-hery** [comment]
I assigned @turolopezsanabria since Bibisirius is in holiday for a week

**Comment by Bibisirius** [comment]
For the design it's done ✅ : [url](https://github.com/adevinta/spark/issues/777)
