### ISSUE TITLE
[Components] Check hover/pressed implementation

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#1501]
Check if we have aligned implementations on all platforms (Android, Figma, iOS, Web). If the states are different compared to the spec, please create implementation tickets.
More information can be found here: https://adevinta.slack.com/archives/C04LNCEMMUN/p1695809868250139?thread_ts=1695734572.383399&cid=C04LNCEMMUN

```[tasklist]
### Tasks
- [ ] Checkbox
- [ ] Radio button
- [ ] Switch
- [x] Slider
```

**Comment by soykje** [comment]
As discussed, the `Slider` component implementation of hover/pressed states has been treated in implementation ticket: https://github.com/adevinta/spark/issues/961
