### ISSUE TITLE
[Components] - using borders instead of box-shadow for outlines

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#1509]
For `focus-visible` (and sometimes `focus`) we are using box-shadows (Tailwind's `ring` API) to display an "outline". The issue is we also use `ring` to display what should be `borders` instead.

I suggest we check the following components 1 by 1 to see if we can replace they "neutral state" (non focused) styles to use proper borders and not box-shadows.

An element can only have one box-shadow, so it also create small visual bugs, exemple on `Button`:

Non-focused:
![Image](https://github.com/adevinta/spark/assets/2033710/20c92646-b9b9-4475-9c0d-1581aff69af4)

Focused:
![Image](https://github.com/adevinta/spark/assets/2033710/ba349a65-612f-4f0d-b8f1-641c062cd158)

=> Notice how once focused, the outlined button loses its border.

List of components to check/update:

- [x] #1528
- [x] Button (outlined design)
- [x] #1532
- [x] #1540
- [x] #1533
- [x] #1531
- [x] #1530
- [x] Tag

**Comment by soykje** [comment]
@elisa-hery Dunno if you'd like to test these refacto tasks... Some have already been merged, but here not: https://github.com/adevinta/spark/pull/1560 👍

**Comment by soykje** [comment]
cc @JeremiasUX @turolopezsanabria Would you like to test it also?

**Comment by soykje** [comment]
Completed!!! 🎉 Thx to all of you 👍
