### ISSUE TITLE
[Components] - Popover - shadow not embracing the arrow

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#1536]
A developer reported that the shadow of the popover is not embracing the shape of the arrow (triangle), which means that the arrow is invisible when used over a white background.

Before:

![Image](https://github.com/adevinta/spark/assets/2033710/b5d0bd42-66dc-44f9-b87e-79e238dcf880)

It's better to use drop-shadow instead:

![Image](https://github.com/adevinta/spark/assets/2033710/9333591c-371f-4059-9347-947f4300b708)

**Comment by thomas-leguellec** [comment]
To discuss with @turolopezsanabria

**Comment by Powerplex** [comment]
Closing as stale
