### ISSUE TITLE
[bug] Desync between Spark theme and Design specs on color scheme

### ISSUE THREAD

**Issue by elisa-hery** [adevinta/spark#1564]
There is a difference of tokens between figma & tailwind config viewer for `onBackground` :

- in [tailwind config viewer](https://sparkui.vercel.app/viewer/), onBackground is #000000
- in [figma](https://www.figma.com/file/ezqkDE3LqYrek9MvYnr4dR/Spark-Foundations?node-id=9056%3A7188&mode=dev) & [spark-tokens repo](https://github.com/adevinta/spark-tokens/blob/bdad6a8e2f248489d103516c62a72c7f83f8424d/tokens/spark/color/figmaTokens.json#L168) onBackground is #1D1F2A

--> `onBackground` should use the following color: `BlackAdevinta 900` (#1D1F2A)

slack thread : https://adevinta.slack.com/archives/C04LNCEMMUN/p1696583537959389

**Comment by soykje** [comment]
@elisa-hery if you want to have a look on fixed color scheme: https://spark-o877om9g0-spark-team.vercel.app/viewer/

**Comment by elisa-hery** [comment]
@soykje ok ✅ (I didn't check every token, just checked the one you updated)

**Comment by soykje** [comment]
@solygambas Just for you to know, we can wait for you if you want to have a final look on this? 🙂
