### ISSUE TITLE
[Component] Select

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark#1579]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark/issues/1634
```

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Risk level ? | critical
Does this ticket need to be design reviewed ? | yes
Referent designer : | ?
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=923-19403&mode=design&t=yhjBUkzyAUuyp1MN-0)
Testing checklist : | [gsheet](https://docs.google.com/spreadsheets/d/1tJClPzFgaZKtgj05iPLosltiRel7PQreEykLDajGjCc/edit#gid=316822420)
UATs : | [to add]()
configurator : | [to add]()

**Comment by elisa-hery** [comment]
List of bugs (and resolution status) is [here](https://docs.google.com/spreadsheets/d/1-wUKejjCAblIpIkE3i7n1dACB3k9qq-kND285N4WwSw/edit#gid=139525665)

**Comment by elisa-hery** [comment]
All bugs listed in the document above have been fixed. 
I'm moving this ticket to RFP 🥳
