### ISSUE TITLE
[Iconography] News icons Polaris Foundation

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#1591]
NEW ICONS - Criterias 

List: [Url](https://www.figma.com/file/Bb9KfyAxvpbSprnUDmWUnt/Polaris-Foundations?type=design&node-id=1-12223&mode=design&t=gS7xcc1GKyEDc9vD-11)

**Cat. Animals:** @abel
- [x] pet-accessory.svg

**Cat. House:**
- [x] baby-furniture.svg

**Cat. Hobbies:**
- [x] collectible.svg
- [x] book.svg
- [x] bike-size.svg

**Cat. Multimedia:**
- [x] computer-accessory.svg
- [x] speaker.svg

**Cat. Vehicles:** @samuel
- [x] gps.svg
- [x] park-assist.svg
- [x] speed-indicator.svg
- [x] keyless-access.svg
- [x] engine-start.svg
- [x] headlight.svg
- [x] rain-sensor.svg
- [x] sunroof.svg
- [x] wheel-rim.svg
- [x] bluetooth.svg
- [x] rearview-camera.svg
- [x] parking-sensor.svg
- [x] seat.svg
- [x] rearview-mirror.svg
- [x] multimedia-system.svg

**Categories:** :[ url](https://www.figma.com/file/Bb9KfyAxvpbSprnUDmWUnt/Polaris-Foundations?type=design&node-id=1-10605&mode=design&t=24qXgri7mybXpXr3-11)
- [x] donation.svg @sarah
- [x] rental.svg @nathalie
- [ ] ❌ placeholder.svg @eli : To be tested. I create a ticket for this case ❌

**Comment by Bibisirius** [comment]
Placeholder : To be tested as it impacts spark components 

For the rest, it's done  ✅

Hi @solygambas

**Comment by solygambas** [comment]
Thank you, see [#94](https://github.com/adevinta/spark-tokens/pull/94)
