### ISSUE TITLE
[Component] AlertDialog review

### ISSUE THREAD

**Issue by andresz1** [adevinta/spark#1616]
**Objetive**

Review AlertDialog specs, give feedback and apply changes if needed

**Comment by elisa-hery** [comment]
Hey @andresz1 I just checked it and it's all good for me : 
- visual quality ✅ 
- responsive ✅ 
- content resilience ✅ 
- functionality ✅ 
- a11y : keyboard navigation ✅ 
- browsers compatibility : checked on chrome (119.0.6045.123), safari (16.6), firefox (119.0.1) ✅ 
- documentation : Zeroheight ✅
