### ISSUE TITLE
Add "inset" prop to Drawer component

### ISSUE THREAD

**Issue by acd02** [adevinta/spark#1654]
There is a common use case in Polaris where users want to have elements within the Drawer component that takes up the full width.

Currently, achieving this requires overriding the internal padding of the component. To prop would make this use case easier and more intuitive.

When set to `true`, this prop will remove the internal padding of the component, allowing for a full-width image or content.

**Comment by elisa-hery** [comment]
@acd02 @soykje will test this ticket as it's not critical
