### ISSUE TITLE
Detailing the styling and theming solution

### ISSUE THREAD

**Issue by andresin87** [adevinta/spark#166]

**Comment by acd02** [comment]
Partially addressed by #213

**Comment by kikoruiz** [comment]
This is one part of the docs: https://github.com/adevinta/spark/blob/main/packages/utils/theme/src/index.stories.mdx, but we should need more docs, specially for the styling side.

I think we can add more documentation when we start to style real components, it's difficult to cover all the needed documentation about styling and theming without having real experience on that.
