### ISSUE TITLE
[Dialog] Img Full width

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#1660]
If  an img  is full width, we place it between the Header and Body, AND the scrollbar is still only applied to the body below
Test : [here](https://stackblitz.com/edit/stackblitz-starters-kz7vss?file=pagesContent%2Findex.tsx)

Follow the topic: [here](https://adevinta.slack.com/archives/C04LNCEMMUN/p1700490869452399)

![Image](https://github.com/adevinta/spark/assets/139967199/bc24ae8a-d45f-4f2b-aacf-26dad746aeb3)

**Comment by acd02** [comment]
Hm, makes me wonder if we actually need an [`inset` prop](https://github.com/adevinta/spark/issues/1652) after all. wdyt, cc @soykje, @andresin87  ,@Powerplex ?

**Comment by acd02** [comment]
actually, I just encountered a use-case within the Polaris codebase where the `inset` prop makes sense still 👍
