### ISSUE TITLE
[Design Specs] Combobox

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#1662]
```[tasklist]
### Tasks
- [x] Figma Documentation
- [x] ZH Documentation
- [x] Create a component
- [x] Add 3 filters: Auto, none & Strict (web) : https://spark-ui-uhip-c6x4544be-sparkteams-projects.vercel.app/?path=/docs/components-combobox--docs#filtering
```

**Comment by Bibisirius** [comment]
Figma : [URL](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=28629-4000&mode=design&t=xpnfd4ER8kswXU3Z-11) (waiting select and dropdown validation)

**Comment by Bibisirius** [comment]
We've identified 3 versions to explore in order to decide which version we're going to start with in V1.

![Image](https://github.com/adevinta/spark/assets/139967199/78ffd69c-394f-4b37-9779-2b30088917b4)

**Comment by JeremiasUX** [comment]
Next steps:

- Sync with @Powerplex and @andresin87

**Comment by Bibisirius** [comment]
### **Agreement** @andresin87 @Powerplex 

- We decided to reduce the padding to **6px** rather than reduce the size of the chips to 28px. 
- We keep **32px for chips** and **padding 6px** for the input area only for multi select

### **Next step:** 

- It will be updated on the component and specs

**Comment by ChrisDesignOps** [comment]
Reviewed and suggested some minor changes

**Comment by Bibisirius** [comment]
Approved by UI ✅
