### ISSUE TITLE
[Bug] - Input - ClearButton positionning broken while input is in error state

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#1666]
https://stackblitz.com/edit/stackblitz-starters-w7xzgh?file=pagesContent%2Findex.tsx

We have an issue when an `InputGroup` with a `ClearButton` goes to error state. The clearButton suddenly have a very large padding/margin to its right.

https://github.com/adevinta/spark/assets/2033710/fa21cfbe-58da-467d-9638-7c4c46bd09f1

**Comment by Powerplex** [comment]
Ok so the issue was not the Clear button position, but the fact that the state indicator (icon) was not displayed when Input is inside a `FormField`.

**Comment by Powerplex** [comment]
Test link: https://spark-k6n0iwuio-spark-team.vercel.app/?path=/docs/components-input--docs#validation

**Comment by elisa-hery** [comment]
After non regression on Stackblitz, recap of the bugs founded : 

<google-sheets-html-origin>
  | Bugs | screenshot
-- | -- | --
1 | GIVEN an input into a formfield <br /> WHEN the input has the error state <br /> THEN the trailing element does not appear |  see video above ⬆️ 
2 | GIVEN an input into a formfield <br />WHEN the input has the error state AND a leading & trailing add-on<br />THEN the add-ons' border is not the right color |  <img width="320" alt="Capture d’écran 2023-11-22 à 12 48 06" src="https://github.com/adevinta/spark/assets/142396647/0da8e140-372b-4f39-a39e-03c632331dfc">
3 | GIVEN an input into a formfield <br />WHEN the input is disabled <br />THEN the add-on and icons (leading and trailing) are not disabled |   <img width="320" alt="Capture d’écran 2023-11-22 à 12 42 06" src="https://github.com/adevinta/spark/assets/142396647/935693fa-2866-420d-a021-b4debf527020">
4 | GIVEN an input into a formfield <br />WHEN the input is readOnly <br />THEN the add-on and icons (leading and trailing) are not read only |  <img width="320" alt="Capture d’écran 2023-11-22 à 12 44 25" src="https://github.com/adevinta/spark/assets/142396647/a57b7642-0ecb-467d-8502-df874cc17a88">

**Comment by elisa-hery** [comment]
Bug fixed ✅
