### ISSUE TITLE
Spark and Polaris DesignOps playbook

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1707]
- [x] Review and detect what's missing @Bibisirius 
- [ ] To refine and add missing information 
- [ ] Add screens
- [ ] Share and valid

**Comment by Bibisirius** [comment]
Figma :[ url](https://www.figma.com/file/RS0WS1ZezJfWGPuy14J4Qx/DesignOps-Playbook?type=design&node-id=1-5494&mode=design&t=KsAjwICppTp2Nlrc-11)

**Comment by turolopezsanabria** [comment]
Moving this task to Jira
