### ISSUE TITLE
[Component Improvement] Selection controls unselect a11y issue

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#1733]
We received feedback regarding an a11y issue with the following components:

- RadioButton unselected
- Checkbox unselected
- Switch unselected

[Report slack](https://adevinta.slack.com/archives/C059UCP6B63/p1701094607874779)
[Report Jira ](https://jira.ets.mpi-internal.com/browse/PT-1907)

[Figma - Exploration](https://www.figma.com/file/epxpKoREcESdwiXgqJPzZY/Test-Spark?type=design&node-id=25-28129&mode=design&t=uhG1zglLoNwfH0EI-4)

- [x] Investigate the issue
- [x] Explore new solutions (if needed)
- [x] Make sure the solution works well 
- [x] Communicate the solution with Design and Spark Devs
- [x] Create Dev tickets
- [x] Update Figma Component, Spec & ZH

**Comment by Bibisirius** [comment]
We're going to do some tests with lBC to find a solution and then we're going to share it

**Comment by elisa-hery** [comment]
The issue has been reported during dark mode testing. Link of the ticket [here](https://jira.ets.mpi-internal.com/browse/PT-1907) (FYI @Bibisirius , I assigned you on the ticket)

**Comment by Bibisirius** [comment]
### Outline darkmode (Nightshade 600 to Nightshade 500)

**Android /iOS:**

- In progress

**Web:**

- To do
