### ISSUE TITLE
[Bugfix] Badge: fix the size for no count

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#1764]
Check please adjust the "no count" version of the badge.

It should be 8px and not 12px as [here](https://sparkui.vercel.app/?path=/docs/components-badge--docs#sizes))

**Comment by soykje** [comment]
I'm not sure to have understood what was finally expected from devs here. So I simply updated size to comply with spec, leaving the alignement topic as it was (right+top aligned, with element's center as reference).
I also proposed some small updates on documentation, if that can help.

**Comment by soykje** [comment]
@elisa-hery @Bibisirius https://spark-ybymct54k-spark-team.vercel.app/?path=/docs/components-badge--docs#sizes For testing purpose :)

**Comment by elisa-hery** [comment]
@Bibisirius it seems ok to me but I think you're the best to do this review 😊

**Comment by Bibisirius** [comment]
It's ok for me ✅ @elisa-hery @soykje
