### ISSUE TITLE
[Component]  Drawer - allow fluid size

### ISSUE THREAD

**Issue by acd02** [adevinta/spark#1829]
see #1802

**Comment by soykje** [comment]
Testing environment: https://spark-m4qozvz24-spark-team.vercel.app/

**Comment by elisa-hery** [comment]
Checked on iPhone 13 (safari & chrome) ✅ 
@Bibisirius you can test !

**Comment by Bibisirius** [comment]
It's ok for me ✅ @elisa-hery @soykje
