### ISSUE TITLE
Helping out Polaris for the Spark migration

### ISSUE THREAD

**Issue by acd02** [adevinta/spark#1830]
This ongoing task, which may extend over multiple sprints, involves navigating the **Polaris** codebase.
The goal is to replace the use of `styled-components` and `Brikke` components with the Tailwind theming solution and Spark components.

**Comment by JeremiasUX** [comment]
https://docs.google.com/spreadsheets/d/1Ab-WQBqqRdTmVyaGyjo1bbjCuwsEGVpUfHVCbQu_JEM/edit#gid=0
