### ISSUE TITLE
[Design Spec] Snackbar

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#1832]
```[tasklist]
### Tasks
- [ ] Spec
- [ ] ZH documentation
- [x] Figma component
```

**Comment by JeremiasUX** [comment]
https://www.figma.com/file/iEiWiQvRPZC09hCSFxsyjo/Brikke-v2?type=design&node-id=494-1846&mode=design&t=QMWN2j9dibrSCYBr-0

**Comment by thomas-leguellec** [comment]
Not a priority for iOS on Q2. Let's put this ticket on Done because it's ok for Web and Android.
We will create a dedicated ticket for iOS later.
