### ISSUE TITLE
[Component] - Dropdown - mouse events disabled inside dialog

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#1838]
Bug is impossible to reproduce on storybook for now. 

Bug is visible on StackBlitz and Polaris.

Issue is known: https://github.com/radix-ui/primitives/issues/1159

Reproduced here: https://stackblitz.com/edit/stackblitz-starters-jbtzge?file=pagesContent%2Fcomponents%2FDropdown.tsx

1. go to "dropdown" tab
2. click on "edit profile"
3. open the dropdown inside the dialog
4. try to scroll or hover items in the dropdown => you can't.

**Comment by elisa-hery** [comment]
Tested and validated ✅ , I'm moving it to RFP (see select & dropdown bugs list [here](https://docs.google.com/spreadsheets/d/1-wUKejjCAblIpIkE3i7n1dACB3k9qq-kND285N4WwSw/edit?usp=sharing))
