### ISSUE TITLE
[Drawer] Screen height on top/right side overlap on Android/iOS devices

### ISSUE THREAD

**Issue by soykje** [adevinta/spark#1840]
If you visit https://www.leboncoin.fr/voitures/offres using an Android or iOS device, you'll have some overlap issues between url address bar and Drawer footer. Seen on Safari, Chrome and Firefox for mobile.

![Capture d’écran du 2024-01-25 11-21-38](https://github.com/adevinta/spark/assets/66770550/57d2714c-0111-434b-837c-e9b1e0de79e3)

**Comment by elisa-hery** [comment]
@soykje tested on iPhone (safari & chrome) and everything is ok ✅ 
Are you able to test it on android ? 👀

**Comment by soykje** [comment]
@elisa-hery I already tested this during and after development stage, with my Android phone using Chrome and Firefox! :slightly_smiling_face: So could we consider it as completed? :smiling_face_with_tear:

**Comment by elisa-hery** [comment]
@soykje yeah ✅ 🥳
