### ISSUE TITLE
[Component] Select option listbox not aligned

### ISSUE THREAD

**Issue by andresin87** [adevinta/spark#1851]
### Description

Options Listbox not aligned with the trigger

### Steps to reproduce

1. Go to https://sparkui.vercel.app/iframe.html?id=experimental-select--default&viewMode=story
2. Open the select field
3. The native list of options is not properly aligned with the trigger

### Spark Component and Version

@spark-ui/select

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

Uploading Grabación de pantalla 2024-01-26 a las 12.55.16.mov…

**Comment by Powerplex** [comment]
I investigated this bug and we should not do anything to fix it.

The position is not only tied to the OS but also the browser.

Fixing it on brikke breaks it on Firefox, Fixing it again breaks it on Safari, etc. Plus, each brother have also difference in behaviour depending if the dropdown has selected values or not.

**Comment by elisa-hery** [comment]
@Powerplex  I'm closing it then !
