### ISSUE TITLE
[Component] - Select - impossible to select first item in unselected state

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#1860]
While fixing bugs for Select, we discovered that when a select has no selected value, the first item in the list already looks selected (check icon) and cannot be selected (the placeholder remain in the trigger).

This is because an HTML select must always have a selected value, at all times. If we don't provide any, it considers the first item to be selected. 

To fix this, I introduce a `Select.Placeholder` item that can be added in the list in the first position. This item is then automatically selected by the browser, instead of the first "real" item.

Before:

https://github.com/adevinta/spark/assets/2033710/0968ecb7-3803-44a8-a2b9-75d5822be9e7

After:

https://github.com/adevinta/spark/assets/2033710/acedcae9-e878-46f5-a544-c3e1a28f39dd

**Comment by elisa-hery** [comment]
tested and validated ✅
