### ISSUE TITLE
[bug][demo app] Tag with long attributed text is not cropped

### ISSUE THREAD

**Issue by elisa-hery** [adevinta/spark#1938]
GIVEN I'm using **UI kit Tag** on demo app on an iPhone
WHEN I select a content with "long attributed text" 
THEN tag doesn't fit the size of the iPhone but goes beyond and is not cropped as it should

note: this bug is only related to the demo app, it should not happen on Polaris or other clients 

![Image](https://github.com/adevinta/spark/assets/142396647/1685b799-145c-4696-832b-05fe3af40252)

**Comment by robergro** [comment]
More Information:

The problem is on this file: **ComponentUIView**
```swift
let widthConstraint = self.contentStackView.widthAnchor.constraint(
    equalTo: self.widthAnchor,
    constant: -spacing * 2
)
widthConstraint.priority = .init(999)
widthConstraint.isActive = true
````

This code must be replaced by:
```swift
NSLayoutConstraint.activate([
    self.contentStackView.widthAnchor.constraint(equalTo: self.widthAnchor, constant: -spacing * 2)
])
```
