### ISSUE TITLE
[Component] FormField - Adjust the colour of the required * star to onSurface

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1955]
Hello, as reported [here](https://adevinta.slack.com/archives/C056PNNGWTY/p1709312447255489) the * is not visible enough.

**Solution**

Adjust the colour
❌ current: onSurface / Dim 3

![Image](https://github.com/adevinta/spark/assets/23620759/41824548-6f79-4d34-a429-7c865f582999)

![Image](https://github.com/adevinta/spark/assets/23620759/76cbc725-6133-4462-86dd-8750e430dd12)

✅ desired: onSurface / Dim 1

![Image](https://github.com/adevinta/spark/assets/23620759/ae20cdda-62fd-46cc-a152-c3627b6fff23)

![Image](https://github.com/adevinta/spark/assets/23620759/c0e56a66-5c0c-4e5e-ab30-341e18f63c8e)

**Comment by elisa-hery** [comment]
I'm closing it, this has already been handled in https://github.com/adevinta/spark/issues/2019
