### ISSUE TITLE
[Button] Loading state - Update the specs to allow for the default option of having only the spinner on the left

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#1957]
We've decided to offer the option to display the `spinner` only on the left. This will maintain consistency with Android constraints.

![Image](https://github.com/adevinta/spark/assets/139967199/a27ea601-8b5a-460c-9279-db66b35fd287)

**Comment by Powerplex** [comment]
We met between web devs and decided that there is no reason to hardcode this limitation in the code as this will add unnecessary complexity. It can remain a Spark/Polaris guidelines and no change is necessary.

**Comment by Bibisirius** [comment]
Okay, noted @Powerplex ! 
In order to maintain consistency with the apps, we'll need to synchronize with the specs only for this point. No need to code it, just remove the loading right in the specs.
