### ISSUE TITLE
[Bug] Slider handler is too small

### ISSUE THREAD

**Issue by elisa-hery** [adevinta/spark#1977]
**🧪 Description / steps to reproduce :** 
GIVEN I'm on Ad detail
WHEN I want to use the slider
THEN it makes me go from one Ad to another

**💯 Expected result :** 
When we move the slider cursor it should not make us go to another page

**⭐️ Useful information (version, browser, other) :** 
N/A

**🧐 Attachments screenshot or video :** 
Issue reported [here](https://adevinta.slack.com/archives/C04QCSQGQUX/p1709632633862359) with videos 

https://github.com/adevinta/spark/assets/142396647/0dc559f4-2073-46dd-83d1-d96cb1a96d37

**Comment by thomas-leguellec** [comment]
New size: 32
