### ISSUE TITLE
[Bug] radio button and chips are not aligned in landscape mode

### ISSUE THREAD

**Issue by elisa-hery** [adevinta/spark#1989]
### Description

On iOS demo app, when radio buttons and checkboxes are vertically aligned,
When I rotate the screen, 
I expected to see radio buttons and checkboxes aligned
But there is a large space in front of radio buttons 

### Steps to reproduce

1. On iOS demo app, Go to 'list'
2. Scroll down and click on 'radio checkbox UI kit'
3. Rotate the screen

### Spark Component and Version

components involved : radio button & checkbox

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![Image](https://github.com/adevinta/spark/assets/142396647/f95eb167-02a6-4e47-b7ac-f58134cec759)

**Comment by thomas-leguellec** [comment]
Remove safe area layout guide for radio-button and chip component.

**Comment by elisa-hery** [comment]
test branch : component/radiobutton_chip_bug_1989

**Comment by elisa-hery** [comment]
Tested with Alican ✅  we will test it again on a dedicated branch with formfield
