### ISSUE TITLE
[Component] Dropdown / Select / Combo-box - change direction of arrow when opened

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#1997]
### Description

Please make the arrow 'chevron' point up if the popover is open.

### Problem Statement/Justification

It's common, and expected behaviour.

### Proposed Solution or API

It can be the same icon, flipped using CSS. There's no need to use a different one.

### Additional Information

Initially requested by Lola [in this thread|https://adevinta.slack.com/archives/C056PNNGWTY/p1711445799323349]

As it is now:
![Mar-26-2024 10-33-27](https://github.com/adevinta/spark/assets/23620759/118e8437-e95f-464d-8798-43c4996e7295)

**Comment by elisa-hery** [comment]
It was done in another ticket, I'm closing this one !

https://github.com/adevinta/spark/assets/142396647/a40fdad8-8677-4006-846a-7a44fddc4351
