### ISSUE TITLE
[Component] - FormField updates

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#2019]
https://spark-ui-uhip-ookpn8avq-sparkteams-projects.vercel.app/?path=/docs/components-formfield--docs#state

- required indicator asterisk went from dim-3 to dim-1
- warning and success message are no longer green and yellow
- status indicator (icon) has been removed from: input, textArea, select, dropdown
- status indicator has been added to FormField messages instead

**Comment by elisa-hery** [comment]
@Powerplex : 

1. required indicator asterisk went from dim-3 to dim-1 ✅ 
2. warning and success message are no longer green and yellow ✅ 
3. status indicator (icon) has been removed from: 
 - input ✅  
 - textArea ❓  I still can see a check icon on text area, is it normal ? (I think text area's specs are not up-to-date yet so I'm not sure)

![Image](https://github.com/adevinta/spark/assets/142396647/7139a1bc-e7a3-429f-932b-8c51238fd133)


 - select ✅  
 - dropdown ✅
4. status indicator has been added to FormField messages instead ✅ 

Design team : it's ready to check ! (@Bibisirius @chuxui)
