### ISSUE TITLE
[Foundation] Clarify the status of elevation

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#2074]
The correctness of the elevation / drop-shadow foundations is unclear. This ticket is used to confirm the correctness of the elevation/drop-shadow.
The question has been raised here in slack: https://adevinta.slack.com/archives/C059UCP6B63/p1713774597596029

- [x] Take a look at the Android, iOS and Web drop-shadow and compare the three to each other
- [x] Take a look at the ZeroHeight and Figma drop-shadow and compare the two to each other
- [ ] Unify drop-shadow
- [ ] Update the changes in all places
- [ ] If necessary, communicate changes to users

**Comment by ChrisDesignOps** [comment]
Reviewed [on this Figma file](https://www.figma.com/file/epxpKoREcESdwiXgqJPzZY/Test-Spark?type=design&node-id=754%3A2070&mode=design&t=Osw7lJZ6GMZs0d29-1):

🖥️🍎 - We are aligned: Only the name changes:

- Design: `drop-shadow-sm`
- Web: `shadow-sm`
- iOS: `small`

🤖 Android: Use Native elevations but are related (not exactly the same) to Design:
Design: `drop-shadow-sm`
Android: `1`
Proposal: Maybe, to be more aligned, on design we can improve the name to: "drop-shadow-sm (🤖1)"


⚠️ But, what’s the behaviour with Native Elevations on Android? I create an exploration [in the Figma file](https://www.figma.com/file/epxpKoREcESdwiXgqJPzZY/Test-Spark?type=design&node-id=787%3A2104&mode=design&t=Osw7lJZ6GMZs0d29-1) to talk about Dark Theme Elevations (maybe not now..). You can see questions for the 3 platforms and a proposal to maybe improve the Elevations to be better on Dark.

**Comment by ChrisDesignOps** [comment]
✅ On Design, iOS, Web, we are aligned

➡️ On Android [devs have to change Elevation naming](https://github.com/adevinta/spark/issues/2108) to be aligned to the rest of the platforms and easy the handoff to android devs.

We will wait to talk about Dark Theme Elevation
