### ISSUE TITLE
[Snackbar] Add bottom button positioning

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#2075]
We received a request for this feature:
- Slack: https://adevinta.slack.com/archives/C059UCP6B63/p1713511075397319
- Spark form: https://docs.google.com/spreadsheets/d/1xDti05i5kp7vwUkCtA-EbLtU0BKZWcZmGpZHvI-Rqqg/edit#gid=1951364618

Requested by: **Cindy**
Deadline: **Second half of Q2**
Platform: **iOS (UiKit and Swift) and Android**
Component: **Snackbar**

What has been requested:
- The team would need to have the button below the content of the snackbar
- On android this is a default behavior https://m3.material.io/components/snackbar/specs#645d590c-af7f-4d7c-8e02-4c755043fa7d

![Image](https://github.com/adevinta/spark/assets/139337913/d60fc131-a68f-498c-8eb3-23ff0daacc2c)

Design - Decision:

- The design team has agreed that this is a valid reason to add this missing feature
- Design team will also push for Snackbar guidelines to make sure the usage is correct

Next steps:

- [x] Update Spec sheet
- [x] Update ZeroHeight
- [x] Update Figma
- [x] Handover to spark developers
- [x] Communicate changes

**Comment by Bibisirius** [comment]
I did the review. I've added some feedback to check

**Comment by Bibisirius** [comment]
Approved ✅

**Comment by ChrisDesignOps** [comment]
Component: Approved ✅ (only some little suggestion that can be avoid)
