### ISSUE TITLE
[Text-view] iOS native component does not provide leading- & trailing-icons

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#2076]
We received a request from the iOS-Spark developers:

- Do we need to provide leading- and trailing-icons for the text-view component in iOS?
- Slack thread: https://adevinta.slack.com/archives/C04LNCEMMUN/p1713866329435419

Issue:

- Native iOS component does not provide the leading- and trailing-icons out of the box
- Android, Web and Figma provides the leading- and trailing-icon
- Features would not be aligned across the platforms -> this could lead to confusions and questions

Goal of this ticket:

- [x] Investigate if there are use cases in production
- [x] Investigate how much work it would be to implement an iOS solution with icon
- [x] Find a solution that won't break after the first use cases

**Comment by ChrisDesignOps** [comment]
[exploration conclusions](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?type=design&node-id=48127%3A6499&mode=design&t=dRy9kvCpofDmhquM-1) We will share it on the next Spark sharing meeting:

1. No external or internal system has a leading & trailing icon in Textview/area.
2. As open source system we have to provide the best solutions. 
3. From Design we don't know now when it was decided to have it in Spark.  
4. Not native on iOS and may break the component if we customize it. 
5. **We have to remove it in Design, Web and Android.**
