### ISSUE TITLE
[Component] Remove deprecated components

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#2079]
![Image](https://github.com/adevinta/spark/assets/139967199/cd8d6d04-57ba-4f71-bfef-cfef487ca1d9)

```[tasklist]
### Tasks
- [x] Checkbox
- [x] Popover
- [x] Radio Button
- [x] Switch
- [x] Tabs
```

**Comment by ChrisDesignOps** [comment]
✅ Deprecated components removed on this [Figma Branch](https://www.figma.com/file/NsGfE3UnbhEyAPpVf3B60P/branch/5WSCe1uLmwKwn2SduZ2V8R/Spark-Components?type=design&node-id=0%3A1&mode=design&t=XuZAe37uaq1xlkC9-1)

**Comment by ChrisDesignOps** [comment]
🗓️ We will merge the branch on **6th May**  (notified on #adv-spark-design)
