### ISSUE TITLE
UI kit - Label alignement issue between radio button & checkboxes

### ISSUE THREAD

**Issue by elisa-hery** [adevinta/spark#2101]
### Description

On demo app, for UI kit, when Radio Button and Checkbox are vertically aligned, their label are **not** aligned.

### Steps to reproduce

1. Go to demo app
2. Click on `list` in the bottom navigation bar > `Radio Checkbox UI kit`
3. See the bug : labels are not vertically aligned

### Spark Component and Version

main branch

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![Image](https://github.com/adevinta/spark/assets/142396647/fab87a0b-2c97-49a0-95d5-61b169adc21d)
![Image](https://github.com/adevinta/spark/assets/142396647/bdc0b6f4-81b5-4a06-9fa5-8f3217397124)

**Comment by aycil-alican** [comment]
Hello, I fixed it. Test branch: component/radiobutton_2101

**Comment by elisa-hery** [comment]
The bug is fixed but we have a weird behavior : 

https://github.com/adevinta/spark/assets/142396647/aad264de-5124-446a-a109-303b1fa6580e

This behavior is also visible on main branch and it's probably linked to demo app, but @aycil-alican is going to check

**Comment by aycil-alican** [comment]
Hello, I checked this and it is related with checkbox group we can move this task if alignment is ok. I created different task for the issue that is in the video.
Bug task: [939](https://github.com/orgs/adevinta/projects/4/views/19?pane=issue&itemId=62989589)
