### ISSUE TITLE
[Component] RadioButton and Checkbox style update

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#2105]
Original ticket: 

- [Component] Align radio button & checkbox style [#1863](https://github.com/adevinta/spark/issues/1863)

Figma:

- https://www.figma.com/file/epxpKoREcESdwiXgqJPzZY/Test-Spark?type=design&node-id=756-5244&mode=design&t=dokDFvciWnFMZRIO-0

Goal:

- Align the style of the not selected radiobuttons and checkboxes with the design (no colour)

**Comment by JeremiasUX** [comment]
@thomas-leguellec task is ready and development can start. Super small task, might take a few min on code side. Should we add this to the next sprint?

**Comment by soykje** [comment]
@michael-zimmermann Why assigning yourself a web ticket? I guess it was a mistake? 🙂

**Comment by soykje** [comment]
@jcatdom @chuxui @JeremiasUX Do you want to review the changes?
- https://spark-ui-uhip-gtg34o6ci-sparkteams-projects.vercel.app/?path=/docs/components-checkbox--docs#intent
- https://spark-ui-uhip-gtg34o6ci-sparkteams-projects.vercel.app/?path=/docs/components-radiogroup--docs#intent

**Comment by JeremiasUX** [comment]
Looks good to me, thanks!
