### ISSUE TITLE
[Component] RadioButton style update

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#2106]
Original ticket: 

- [Component] Align radio button & checkbox style [#1863](https://github.com/adevinta/spark/issues/1863)

Figma:

- https://www.figma.com/file/epxpKoREcESdwiXgqJPzZY/Test-Spark?type=design&node-id=756-5244&mode=design&t=dokDFvciWnFMZRIO-0

Goal:

- Align the style of the not selected radiobuttons with the design (no colour)

**Comment by JeremiasUX** [comment]
@thomas-leguellec task is ready and development can start. Super small task, might take a few min on code side. Should we add this to the next sprint?

**Comment by michael-zimmermann** [comment]
Fixed with #2101
