### ISSUE TITLE
[Token] Elevation naming

### ISSUE THREAD

**Issue by ChrisDesignOps** [adevinta/spark#2108]
### Description

Change Elevation token naming on Android

### Problem Statement/Justification

- Android is not in sync with the rest of the platforms on Elevation (design/web/iOS) 
- We need to easy the handoff to Android devs 

### Proposed Solution or API

[Elevation Specs on ZH](https://spark.adevinta.com/1186e1705/p/39675a-elevation)

[Design elevation vs related Android current elevation](https://www.figma.com/file/epxpKoREcESdwiXgqJPzZY/Test-Spark?type=design&node-id=800%3A3851&mode=design&t=VAj3LV7frA4yLqKW-1) 

### Additional Information

Reference:
this [Slack thread](https://adevinta.slack.com/archives/C04LNCEMMUN/p1714661429927179)

**Comment by thomas-leguellec** [comment]
Not possible to change that on Android, it's a native behavior on Android.
