### ISSUE TITLE
[Storybook] Check the read only as there is a bug

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#2136]
We currently have the option of having a disabled and enabled style by default in the Select.

Example: ![Image](https://github.com/adevinta/spark/assets/139967199/2a9802d3-6a40-46e6-9196-e4a65903897b)

There is currently a bug in the read-only style on the select, which needs to be corrected to maintain consistency.

- By default, the read-only style will be disabled. 
- If necessary, we can also use the enable version.

![Image](https://github.com/adevinta/spark/assets/139967199/9029be0e-ff43-4379-a612-a365a3bde08a)

**Comment by soykje** [comment]
If I'm not wrong we also have similar issue with `disabled` state for the `Select`. Both will be fixed in this ticket 👍

**Comment by soykje** [comment]
@Bibisirius cc @JeremiasUX https://spark-ui-uhip-k18p5l0o8-sparkteams-projects.vercel.app/?path=/docs/components-select--docs#read-only 👍

**Comment by Bibisirius** [comment]
Check and approved ✅
