### ISSUE TITLE
[Snackbar] item layout update (RWD)

### ISSUE THREAD

**Issue by soykje** [adevinta/spark#2147]
Following design specs update, we want to improve item layout following way:
![Image](https://github.com/adevinta/spark/assets/66770550/3379fba4-b50d-4920-ac59-283f4ddda4f3)

For more infos: https://www.figma.com/design/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?node-id=43448-28117&t=7KNS8UY1D2Fu3ifo-4

**Comment by soykje** [comment]
@jcatdom @JeremiasUX Here is the link to test incoming changes: https://spark-ui-uhip-gt7bvtwv6-sparkteams-projects.vercel.app/?path=/docs/components-snackbar--docs#action

**Comment by jcatdom** [comment]
> @jcatdom @JeremiasUX Here is the link to test incoming changes: https://spark-ui-uhip-gt7bvtwv6-sparkteams-projects.vercel.app/?path=/docs/components-snackbar--docs#action

@soykje can we have a snackbar sample with action in a new line + close button?

**Comment by soykje** [comment]
> > [@jcatdom](https://github.com/jcatdom) [@JeremiasUX](https://github.com/JeremiasUX) Here is the link to test incoming changes: https://spark-ui-uhip-gt7bvtwv6-sparkteams-projects.vercel.app/?path=/docs/components-snackbar--docs#action
> 
> [@soykje](https://github.com/soykje) can we have a snackbar sample with action in a new line + close button?

@jcatdom We use to only demonstrate one property/feature per section, to keep things more understandable... Is there any blocking point not having this additionnal closing button within this action dedicated example?

**Comment by jcatdom** [comment]
> > > [@jcatdom](https://github.com/jcatdom) [@JeremiasUX](https://github.com/JeremiasUX) Here is the link to test incoming changes: https://spark-ui-uhip-gt7bvtwv6-sparkteams-projects.vercel.app/?path=/docs/components-snackbar--docs#action
> > 
> > 
> > [@soykje](https://github.com/soykje) can we have a snackbar sample with action in a new line + close button?
> 
> @jcatdom We use to only demonstrate one property/feature per section, to keep things clearer and more understandable... Is there any blocking point not having this additionnal closing button within this action dedicated example?

@soykje Nop, there isn't any blocker, it was saying only to see the result. OK for me

**Comment by soykje** [comment]
@jcatdom Got it! I just added a "secret story" that you can check [here](https://spark-ui-uhip-pcrhlbc76-sparkteams-projects.vercel.app/iframe.html?id=components-snackbar--qa-with-new-line-action&viewMode=story) 👍 It includes the wanted implementation for QA purpose... hope that will be good for you! 🙂

**Comment by jcatdom** [comment]
> @jcatdom Got it! I just added a "secret story" that you can check [here](https://spark-ui-uhip-pcrhlbc76-sparkteams-projects.vercel.app/iframe.html?id=components-snackbar--qa-with-new-line-action&viewMode=story) 👍 It includes the wanted implementation for QA purpose... hope that will be good for you! 🙂

@soykje really thank you! nice and smooth, one question: 
- Text increases the width to the Button instead to Close action
![Uploading Captura de pantalla 2024-05-23 a las 15.13.56.png…]()
, I mean avoiding text width increasing with Button visible and hidden?

**Comment by soykje** [comment]
If I understood correctly, it would be something more like this?
![image](https://github.com/adevinta/spark/assets/66770550/20d74fba-2667-44e8-9b65-9320438f8584)

**Comment by jcatdom** [comment]
> If I understood correctly, it would be something more like this? ![image](https://private-user-images.githubusercontent.com/66770550/333208571-20d74fba-2667-44e8-9b65-9320438f8584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDA0MzUsIm5iZiI6MTcxNjU0MDEzNSwicGF0aCI6Ii82Njc3MDU1MC8zMzMyMDg1NzEtMjBkNzRmYmEtMjY2Ny00NGU4LTliNjUtOTMyMDQzOGY4NTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA4NDIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZDI5OGY1ZTJkODM4MDVhMzRkY2YwZTI0N2UxMDQ0NDI1NTRkZTBlYjc4MzYzNjM2ZDhhYzQ5MTA1NDM2ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1FPSeQfDQLZxm1Atao__gETKGpDFTw3C8zA3WnKFu0Q)
> 
> You can check the update just [here](https://spark-ui-uhip-3q91eusxd-sparkteams-projects.vercel.app/iframe.html?id=components-snackbar--qa-with-new-line-action&viewMode=story)! 👍

Yes perfect 👌🏼
![Captura de pantalla 2024-05-24 a las 10 44 07](https://github.com/adevinta/spark/assets/94112525/c324003e-87ef-4ae4-9cac-7141181c8862)
