### ISSUE TITLE
[Improvement] Text view

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#2157]
Form field needs to be updated:

- [ ] Discuss if we should remove icons in the text view.

More info:

- [Exploration conclusions](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?type=design&node-id=48127%3A6499&mode=design&t=dRy9kvCpofDmhquM-1) We will share it on the next Spark sharing meeting: 

- No external or internal system has a leading & trailing icon in Textview/area.
- As open source system we have to provide the best solutions.
- From Design we don't know now when it was decided to have it in Spark.
- Not native on iOS and may break the component if we customize it.
- We have to remove it in Design, Web and Android.

**Comment by Bibisirius** [comment]
Move on the ticket: [Issue 2166](https://github.com/adevinta/spark/issues/2166)
