### ISSUE TITLE
[Component] - Popover: intents

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#2163]
Figma for `Popover` shows support for `intent` prop (colors): https://www.figma.com/design/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?node-id=44746-2420&t=9S43WmMJKh0EV9wB-4

We did not implement this in the first version of the popover.

**Comment by elisa-hery** [comment]
test link is https://spark-ui-uhip-i2n41ywta-sparkteams-projects.vercel.app/?path=/docs/components-popover--docs

**Comment by Bibisirius** [comment]
The intent popover  is  approved   ✅  @Powerplex @elisa-hery
