### ISSUE TITLE
[Foundations] Improve Shadows documentation and DarkMode elevations

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#2176]
We don't provide DarkMode shadows and the shadows are not visible in DarkMode.

- https://spark.adevinta.com/1186e1705/p/39675a-elevation
- https://adevinta.slack.com/archives/C04LNCEMMUN/p1716819958409859

- [x] Improve the existing documentation based on RE work
- [x] Create DarkMode shadows
- [x] Update Foundations
- [x] Document in ZH
- [x] Share the improvement

**Comment by JeremiasUX** [comment]
New answers here: https://adevinta.slack.com/archives/C04LNCEMMUN/p1716819958409859

**Comment by JeremiasUX** [comment]
Spark Foundation branch can be found here: 
- https://www.figma.com/design/ezqkDE3LqYrek9MvYnr4dR/branch/IhuHDOyPbBmqUTXw3T5PG9/Spark-Foundations?m=auto

Design exploration:
- https://www.figma.com/design/epxpKoREcESdwiXgqJPzZY/Test-Spark?node-id=1193-16781&t=SH8SyxlNu672kvND-0

Current solution - not perfect :
- Android uses the material shadow
- iOS uses white color in dark mode

**Comment by lauragautheron** [comment]
assigned to @sarah hattab
