### ISSUE TITLE
[Spec] Improve Form Field

### ISSUE THREAD

**Issue by JeremiasUX** [adevinta/spark#2222]
The FormField spec does not reflect all lates decisions:

- [x] Update figma spec
- [x] Add spec to ZH

**Comment by ChrisDesignOps** [comment]
✅ Specs updated & [added to ZH](https://zeroheight.com/1186e1705/v/latest/p/423a01-form-field)

**Comment by ChrisDesignOps** [comment]
✅ FormField specs are now updated in [Figma](https://www.figma.com/design/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?node-id=44899-1283&t=WJ3nJSLBGFSkqUS3-1) & [ZH](https://spark.adevinta.com/1186e1705/p/423a01-form-field) !
