### ISSUE TITLE
[Component] FormField HelpText

### ISSUE THREAD

**Issue by ChrisDesignOps** [adevinta/spark#2233]
### Description

When the FormField HelpText have a long text I expected that the icon of the HelpText maintain the size in a small devices but the size of the icon scales instead.

![Image](https://github.com/adevinta/spark/assets/81374770/6a09a606-807a-43ed-b49d-517d05c90fb0)

### Steps to reproduce

1. Go to '[FormField States](https://spark-ui-uhip-irzqkddp0-sparkteams-projects.vercel.app/?path=/docs/components-formfield--docs)'
2. Change HelpText span with a long text
3. Reduce the browser width

### Spark Component and Version

@spark-ui/textfield

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by elisa-hery** [comment]
slack thread : https://adevinta.slack.com/archives/C071PA3MWAK/p1718366076182249

**Comment by elisa-hery** [comment]
✅ i'm moving it to done !

![Image](https://github.com/adevinta/spark/assets/142396647/4bff4d11-794c-4d98-a23d-bfa049ba06f5)
