### ISSUE TITLE
[Badge] Update the component Figma

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark#2234]
There were several errors on the component:

- The **"no stroke**" property was not correct.
- The "Count" property had been removed from the **"secondary"** property

![Image](https://github.com/adevinta/spark/assets/139967199/2ba8ca65-a81c-425b-9424-e0fee2bf1984)

![Image](https://github.com/adevinta/spark/assets/139967199/d4f020be-12ae-464d-a3ea-42b06ffbffbb)

**Comment by Bibisirius** [comment]
Ready for review @ChrisDesignOps @jcatdom  @JeremiasUX 

Figma: https://www.figma.com/design/NsGfE3UnbhEyAPpVf3B60P/branch/OriVh2j9PhzfLgSd9DDDet/Spark-Components?node-id=247-4718&t=3mVSz6uyLa9yNRlH-11

**Comment by JeremiasUX** [comment]
Approved, looks good to me ✅
