### ISSUE TITLE
[Component] - Breadcrumb

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#2366]
Specs: https://www.figma.com/design/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?node-id=51823-4174&t=2KJd1NtzLyWcHj66-4

UATs: https://docs.google.com/spreadsheets/d/1lLudlD-Qf9hUuLxgOJ8IqWkQoIHCV2YuQPBIUiQPIjs/edit?gid=1511072681#gid=1511072681

Storybook link (preview): https://spark-ui-uhip-q8jp9gdwv-sparkteams-projects.vercel.app/?path=/docs/experimental-breadcrumb--docs

**Comment by elisa-hery** [comment]
@Powerplex 2 remarks : 
1. On safari I don't manage to navigate on breadcrumbs with keyboards, do you have the same issue ?
https://github.com/user-attachments/assets/00dad1ba-9091-4b95-848e-504a3604f9bb

2. We cannot test the case when bredcrumb goes next line (UAT 1.4.1)

**Comment by elisa-hery** [comment]
1. it's not only about breadcrumbs, it's about all links for safari 17.5. @Powerplex is investigating
2. I was able to test on a really small screen and it's ok

@lauragautheron has validated on her side (see slack message [here](https://adevinta.slack.com/archives/C07FHD6M42X/p1723554895589579)).

I'm moving this ticket to RFP !

**Comment by elisa-hery** [comment]
issue identified : https://adevinta.slack.com/archives/C04BKBEKM34/p1724144792997869
