### ISSUE TITLE
[Theme] - new default color scheme for Spark themes

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#2375]
Now that Polaris is stopped, color scheme for both themes (light and dark) must be aligned to Figma: https://www.figma.com/design/NsGfE3UnbhEyAPpVf3B60P/Spark-Design-System?m=auto&node-id=17755-40830&t=91JH6nzwbsRE8UWl-1

This new color scheme is using Leboncoin-related colors by default.

**Comment by Bibisirius** [comment]
### Review of New Default Color Scheme for Spark Themes

**Just one correction needed:**

**Checkbox:**

- The background color of the custom version doesn’t match the invisible checkbox. 

![Image](https://github.com/user-attachments/assets/69a890cb-2c3a-47cf-a81b-8a6d2fcd6058)

- Please use the Radio button group as a reference.


![Image](https://github.com/user-attachments/assets/4606278a-0f21-4aa4-92d7-0aeaa996e166)

**Everything else is approved ✅**
