### ISSUE TITLE
Refine the list of required components for end of Q2

### ISSUE THREAD

**Issue by andresin87** [adevinta/spark#25]

**Comment by thomas-leguellec** [comment]
Inventory: 
https://docs.google.com/spreadsheets/d/1Rso3tOeMnwB0XGS8kN-WHPjrYhJDz81RUuQCGHps47w/edit#gid=879983224

FT Reco :
- [ ] Home - Web
- [ ] Home - iOS

FT Search :
- [ ] Listing - Web
- [ ] Listing - iOS

FT Pro-Ads :
- [ ] Adview - Web
- [ ] Adview - iOS

FT Adlife :
- [ ] Ad insertion - Web
- [ ] Ad insertion - iOS

FT Authent :
- [ ] Auth - Web
- [ ] Auth - iOS

FT Contact :
- [ ] Messaging - Web
- [ ] Messaging - iOS

**Comment by turolopezsanabria** [comment]
@thomas-leguellec 
Do we have all the info for FT Contact too?
