### ISSUE TITLE
Optimize DS configuration for users

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#264]

**Comment by acd02** [comment]
The current setup process for our design system can be a bit cumbersome 🫤

Therefore, we want to simplify the process and make it more user-friendly, in the hope of improving the overall adoption of our DS

**Comment by arnau-rius** [comment]
should we have a Document DS configuration task?

**Comment by arnau-rius** [comment]
Like a how to guide?

**Comment by acd02** [comment]
Sure, once it's merged, I'll update the existing doc 👍
