### ISSUE TITLE
Get the definitive list of browsers that we must support

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#280]
- [x] SUI browser support
- [x] Leboncoin browser support
- [x]  Ebay-K browser support

**Comment by arnau-rius** [comment]
I think that we don't have a official documentation but we last note I have is: For Spain it is Chrome >= 49, Safari >= 11, Edge >= 16, Firefox >= 52, Android Browser >= 4.4.4

**Comment by Powerplex** [comment]
[DE browser coverage](https://browsersl.ist/#q=%3E+1%25+in+DE+or+last+2+years+and+supports+async-functions)
[ES browser coverage](https://browsersl.ist/#q=Chrome+%3E%3D+49%2C+Safari+%3E%3D+11%2C+Edge+%3E%3D+16%2C+Firefox+%3E%3D+52%2C+Android+%3E%3D+4.4.4)
[FR current coverage](https://browsersl.ist/#q=last+3+versions%2C+ie+%3E%3D+11%2C+safari+%3E%3D+4%2C+android+%3E%3D+4)

**Comment by arnau-rius** [comment]
Here is the 
[Radix browser coverage](https://browsersl.ist/#q=Chrome+%3E%3D+74%2C+Safari+%3E%3D+13.1%2C+iOS+%3E%3D+13.3%2C+Firefox+%3E%3D+78%2C+Edge+%3E%3D+79) from this https://github.com/radix-ui/primitives/blob/8f75e5be679b9c269638bddf532a166d80edecb4/babel.config.js#L30

**Comment by arnau-rius** [comment]
DE browser adapted to Europe: https://browsersl.ist/#q=%3E+1%25+and+supports+async-functions%2C+not+dead&region=alt-eu

Radix and DE Browser Coverage have in common: Chrome, Safari, Safari on IOS, Firefox and Edge.
DE Coverage > 1 and not in Radix (explicitly): Samsung Internet

**Comment by arnau-rius** [comment]
Now, we need to implement this in the repository so we make sure that the resulting build that users will use is compliant what we have defined here: https://github.com/adevinta/spark/issues/347
