### ISSUE TITLE
Security: permissions management

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark#320]
We need to investigate of how we can manage the users and their permissions. The goal is to be able to link a user with Okta. Maybe we can do a cron which push the users and their roles.

**Comment by thomas-leguellec** [comment]
In the future, Okta will be plugged to GH. We keep this ticket in the backlog for now.

**Comment by andresin87** [comment]
Bob Moghimi
Thibault Jamet

@bmoqimi @tjamet 

we are talking about that on slack #github-com-adevinta-owners private channel
