### ISSUE TITLE
[Tech] Security: vulnerabilities

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark#321]
We need to plug Vulcan which is a set of tools developed by the Spanish security team (more info here #vulcan-dev)

**Comment by thomas-leguellec** [comment]
Laval tool can directly be integrated to the CI/CD.

**Contact:** 
Alejandro Fernandez
manuelalejandro.fernandez@adevinta.com

**Comment by andresin87** [comment]
Vulcan can be setup
It parses all the assets (deployed urls, repositories, etc) configured
- It is not prepared for public repositories. We might clone the repo in our enterprise private gh and sync it daily. I discovered [this](https://github.com/marketplace/actions/fork-sync) action which can done it automatically.
Lava is WiP.
- We will be able to get enrolled during Q42023

**Comment by andresin87** [comment]
#1583 Stage-0
