### ISSUE TITLE
Definition of Ready

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark#409]

**Comment by kikoruiz** [comment]
I think we need to write how a issue description has to be for each type of task: "user story", "bug" and "spike". Anything else or different?

**Comment by kikoruiz** [comment]
And maybe we could use Issue Templates: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository, WDYT?
