### ISSUE TITLE
Definition of Done - Remove atomic design reference

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#507]
There's a reference to Brad Frost's Atomic design principles in the documentation, but we **don't** split or organise components in atoms, molecules, etc

**Where:**
https://sparkui.vercel.app/?path=/docs/practices-component-definition-of-done--docs

**Comment by Powerplex** [comment]
@turolopezsanabria I would like to discuss this one with you :) 

The components are not grouped in the sidebar using atomic design principle, but this doc is more for us (Spark contributors) to know to use composability or not, and which type of components belongs in Spark.

Basically:
- Atom: no composability required
- Molecules + Organisms = composability required
- Templates + Pages = does not belong in Spark.

Maybe we can write it a different way ?

**Comment by turolopezsanabria** [comment]
Sure, open to discuss for sure, but atomic naming (Atoms molecules etc)has been and is a pain in real life. 
Sounds good in paper, but just for marketing of DS.

How does it help with drawing a line yo understand which component belongs to spark? 

Here an example:

![image](https://user-images.githubusercontent.com/23620759/233166901-883d6d76-b846-4154-84fe-0561eea3dced.jpeg)

**Comment by turolopezsanabria** [comment]
Oh sorry, the screenshot was in Spanish. The example:

- Someone needs to create a 'Video player' that will be a combination of smaller parts, and will receive a different video depending on the provider (Vimeo, YouTube, etc)
- it won't be a combination of other atoms of the system, but it will in fact be a combination of elements.

If we follow the mental model of Atomic Design
❌ It can't be named 'atom' because it will have many parts
❌ Ir can't be a 'molecule' because it's not a combination or atoms

- 

On top of that, we will start running down the rabbit hole with questions such as:
- "What is a checkbox?" And "What is a checkbox + its label?", and "what is a dropdown-option with a checkbox with label inside?", etc 
- "What is a tag?" and "What is a tag with a numbers badge inside?"
Etc 

- 

Atomic design is just a mainstream name for old Modular Design.

I prefer we call every single thing what it actually is, and combine the different pieces logically. 
- A Token is a token 
- A Component is a component 
- A hook is a hook
- Etc  

We can always ask:
Is this 'component' a composition of other 'components'?: true / false.

May I suggest we find a name for the components that are a combination of components?

**Comment by turolopezsanabria** [comment]
✅ review done, thank you
