### ISSUE TITLE
[Components] Button loading state

### ISSUE THREAD

**Issue by andresz1** [adevinta/spark#539]
### Description

Buttons should provide a loading state option to let the users know that something is happening

### Problem Statement/Justification

I believe it's important to include this feature because it provides users with immediate feedback, even if the desired result is not immediately visible. This way, users are aware that the system is processing their request and can continue to interact with it without feeling uncertain or confused.

### Proposed Solution or API

Two props:
- `isLoading` will display a spark spinner
- `loadingText` optionally set some text when the button is in the loading state

```jsx
<>
<Button isLoading>
  Email
</Button>

<Button isLoading loadingText="Submitting">
  Submit
</Button>
</>
```

![Screen Shot 2023-04-03 at 13 08 23](https://user-images.githubusercontent.com/6877967/229493626-d22a6c54-4a29-4e57-987b-3a967794b038.png)

**Comment by andresin87** [comment]
loading text maintains the button with given with default (non-liading) children?
