### ISSUE TITLE
[Components] Button - icons (left/right)

### ISSUE THREAD

**Issue by andresz1** [adevinta/spark#540]
### Description

Add icon support to the button component

### Problem Statement/Justification

At this moment we can not add icons to the buttons easily. We should provide a way to do it. The button can have a right and/or a left icon and the size of them should be synchronized with the size of the button.

### Proposed Solution or API

```jsx
<>
  <Button leftIcon={<EmailIcon />}>
    Email
  </Button>
  <Button rightIcon={<ArrowForwardIcon />}>
    Call us
  </Button>
</>
```

**Comment by Powerplex** [comment]
@andresz1 for now maybe we can continue with composability instead of leftIcon/rightIcon ?

Because if we do it for the Button, why not doing it also for the Radio, Checkbox, etc ? (consistency)
