### ISSUE TITLE
[Components] Button - Icon Only

### ISSUE THREAD

**Issue by andresz1** [adevinta/spark#541]
### Description

Icon Button composes the Button component except that it renders only an icon. Since Icon Button only renders an icon, you must pass the aria-label prop, so screen readers can give meaning to the button

### Problem Statement/Justification

We need this component because if not aria-label could not be used. Besides choosing between `rightIcon` and `leftIcon` for an Icon Button could be confusing for our users

### Proposed Solution or API

```jsx
<IconButton aria-label='Search database' icon={<SearchIcon />} />
```

**Comment by turolopezsanabria** [comment]
Cool!
Will this component make use of the `VisuallyHidden` component? 
Remember to force square aspect ratio to buttons if only icon

**Comment by turolopezsanabria** [comment]
✅ OK design review

I'll split the Design and ZH documentation from the other buttons
