### ISSUE TITLE
[Components] Tabs

### ISSUE THREAD

**Issue by soykje** [adevinta/spark#544]
![image](https://user-images.githubusercontent.com/66770550/233297720-b43323d6-8ce4-47b0-8f8f-b6695684acc7.png)

**Comment by soykje** [comment]
Both technical and design reviews on their ways 🚀

**Comment by turolopezsanabria** [comment]
✅ OK design review

**Comment by turolopezsanabria** [comment]
✅ OK design review

**Comment by turolopezsanabria** [comment]
- In story "intent" add labels to each example
- We need lables for the sizes as well.
- The label for States could change to Disabled state
- Update the prop icon to reflect that now are childrens (like chips)
- Add which one is the default in all black.

**Comment by soykje** [comment]
Everything has been updated. Waiting for final reviews!
