### ISSUE TITLE
Storybook - cache issue blocking loading of components

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#554]
Happening often in dev mode, not in production:

![image](https://user-images.githubusercontent.com/66770550/230029134-f6ff2651-fe54-4d66-a399-9c906e900bce.png)

**Comment by soykje** [comment]
I don't understand our Vite setup, neither the purpose of the `react-vite` package... Official documentation suggests to install the builder specifically: `https://storybook.js.org/docs/react/builders/vite` Would be happy to discuss with any expert from the team! :smile:

**Comment by Powerplex** [comment]
It comes from the `@spark-ui/icons` components. For some reasons storybook tries to load hundrers of icons (every icon) from cache, and it fails.
