### ISSUE TITLE
Discussion about buttons' colours

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#555]
The current approach for buttons, tags, etc is following the rule of:
- Brand colour  = Primary
- Secondary brand colour = Accent

I'm not sure it's the right approach from the design perspective, and I want to make sure we both agree on it @mathieuhervouetlbc

**Comment by mathieuhervouetlbc** [comment]
For LBC if we want to put accent on an item we use Primary one (the brand color)
