### ISSUE TITLE
Base Textarea Component

### ISSUE THREAD

**Issue by andresin87** [adevinta/spark#765]
### Description

The `TextArea` component should render the native `Html TextArea` only.
The package will be named `@spark-ui/textarea`

take a look on #760 

### Problem Statement/Justification

We need to spread and decouple all the pieces in a very small parts to be able to compose all of them.

### Proposed Solution or API

The way it will be uses is for self using that element for composing custom renders:

### ***Scenario 7***: TextBlock look like a multiline TextField as a TextBlockField
```jsx
<TextBlockField>textarea label</TextBlockField>
```
this will be equivalent to:
```jsx
<Input.Group>
	<FloatingLabel>
		<TextArea /> <--this is what we need
	</FloatingLabel>
</Input.Group>
```

### Additional Information

https://mui.com/base/react-textarea-autosize/

**Comment by andresz1** [comment]
https://github.com/adevinta/spark/pull/881

**Comment by soykje** [comment]
As PR has been merged, couldn't we close this issue now? cc @andresz1

**Comment by andresz1** [comment]
Yup
