### ISSUE TITLE
TextBlockField

### ISSUE THREAD

**Issue by andresin87** [adevinta/spark#767]
### Description

take a look on #766 

The idea is to achieve a compoennt witha similar look and field but it needs to manage a simple way og installing a simple text-area labeled and completely accessible.

### Problem Statement/Justification

Compose an easy way of creating accesible text block fields.

### Proposed Solution or API

```jsx
<TextBlockField value="value" required="*">label</TextBlockField>
```

...is the same as...

```jsx
<InputGroup>
  <FloatingLabel label="label" required="*">
    <TextArea value="value"/>
  </FloatingLabel>
<InputGroup>
```

**Comment by andresz1** [comment]
Should we close this issue ? cc @andresin87
