### ISSUE TITLE
How to deal with forms and fields

### ISSUE THREAD

**Issue by andresin87** [adevinta/spark#768]
### Description

Our colleges (fontend devs) most of the time expends many time handling a proper way of mocking forms. There are many variables to attend in order to make them work properly. The main goal to achieve is create a simple solution that satisfies its challenges improving its DX making them love @spark-ui DS.

### Problem Statement/Justification

We need to include a very clear documentation with multiple examples mixing different fields attending a perfect accesibility for all diferent situations.

### Proposed Solution or API

Combine
- Checkboxes
- Radio
- TextFields
- Complex Inputs
	- Input.Elements, Input.Addons, Icons and Buttons
- TextBlockFields
- Inputs manually labeled

Alltogether needs to be wraped properly with the FormField with its helper-message and error-message

**Comment by andresz1** [comment]
Should we close this issue ?

**Comment by andresin87** [comment]
Yup!
