### ISSUE TITLE
[Design Specs] Modal / Dialog

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#777]
- [x] [Specs in Figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=6255-36810&mode=design) in progress
- [x] [ZeroHeight Documentation](https://spark.adevinta.com/1186e1705/p/2427e1-modaldialog)
- [x] Add the specific features of Android 
- [x] Merge and publish 

The component : [here](https://www.figma.com/file/NsGfE3UnbhEyAPpVf3B60P/Spark-Components?type=design&node-id=8621-11678&mode=design&t=X5VjEHzXCL6tIvUM-11)

**Comment by Bibisirius** [comment]
On going test design : [Draft](https://www.figma.com/file/tvtwKEryrq6PTnbyDw5MRr/Dialog-test?type=design&node-id=1-796&mode=design&t=nIU3ZO63SRh7ukvf-11)

**Comment by Bibisirius** [comment]
Waiting Android specifications

**Comment by Bibisirius** [comment]
Dialg spec are ready : [here](https://zeroheight.com/1186e1705/v/latest/p/2427e1-modaldialog/b/02a6bc)

**Comment by Bibisirius** [comment]
**Adjust the placeholder in 2 versions:**

- With padding
- Without padding

Hi @Powerplex

**Comment by Bibisirius** [comment]
It's done for design ✅
