### ISSUE TITLE
The demo of Checkbox is broken 

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#808]
### Description

The demo of the checkbox in StoryBook is broken

### Steps to reproduce

1. Go to https://sparkui.vercel.app/?path=/docs/components-checkbox--docs
2. See error

### Spark Component and Version

@spark-ui/checkbox

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![Captura de Pantalla 2023-05-24 a las 17 28 11](https://github.com/adevinta/spark/assets/23620759/ee93f7ef-73e8-4611-b15c-d5d7c3d442ac)

**Comment by acd02** [comment]
@turolopezsanabria, I'm not able to reproduce the issue you're experiencing.

But unfortunately, what your screenshot shows tends to happen quite often. When this occurs, the remedy is to simply refresh the page 😅

**Comment by turolopezsanabria** [comment]
Top 😂😂🤣
I used the "refresh" technique and worked, thnx!
