### ISSUE TITLE
[Polaris] - Spark theme preview for the board

### ISSUE THREAD

**Issue by Powerplex** [adevinta/spark#811]
The goal is to provide an environment for end of June where leboncoin has a different color scheme and english (i18n) wordings.

We did the color scheme part by publishing a customized version of legacy themes (not spark themes).

**Comment by thomas-leguellec** [comment]
https://polaris-color-swap-demo.next.ariane.leboncoin.ci/

**Comment by thomas-leguellec** [comment]
Ok for all the needed screens: https://demo-polaris.next.ariane.leboncoin.ci/
