### ISSUE TITLE
[Component] Icon-button A11y - Add label on long-press and hover

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark#815]
### Description

Is it possible to see the label description of the `icon-button` on hover / long press for A11y?
Same as what Material does, check this link:
https://m3.material.io/components/icon-buttons/guidelines#47fcd0ba-4390-4d5f-8fe3-905c5795c47f

### Problem Statement/Justification

I think it was coded already, but it doesn't work, at least in the demo of Storybook.

### Proposed Solution or API

--

**Comment by soykje** [comment]
@turolopezsanabria If I understand correctly the Material example is about `hover` only, right? Also, maybe a silly question but couldn't we complete the need with a simple `title` standard attribute here? 🤔
