### ISSUE TITLE
[Components] Button and IconButton style update

### ISSUE THREAD

**Issue by soykje** [adevinta/spark#830]
### Description

To improve our DS consistency, we want to harmonize border sizes. As visible in [Figma specs](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=2340-22556&t=xkErzPSGZ3TXhuHG-0), we now want `Button` and `IconButton` components to have a 1px border size.

### Problem Statement/Justification

To improve our DS consistency, we want to harmonize border sizes. As visible in [Figma specs](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=2340-22556&t=xkErzPSGZ3TXhuHG-0), we now want `Button` and `IconButton` components to have a 1px border size.

### Proposed Solution or API

As visible in [Figma specs](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=2340-22556&t=xkErzPSGZ3TXhuHG-0), we now want `Button` and `IconButton` components to have a 1px border size.

**Comment by soykje** [comment]
@mathieuhervouetlbc @turolopezsanabria Ready for Design Review: https://spark-65pzi1tst-spark-team.vercel.app/?path=/docs/components-button--docs#design

**Comment by turolopezsanabria** [comment]
Parfwct! Merci
