### ISSUE TITLE
[Fixes] Icons

### ISSUE THREAD

**Issue by mathieuhervouetlbc** [adevinta/spark#851]
![Image](https://github.com/adevinta/spark/assets/23620759/d9255d70-dba6-49b9-ae36-eecfe9617247)
![Image](https://github.com/adevinta/spark/assets/23620759/99a9486b-99e6-4665-afe7-2f07aea3bc64)
![Image](https://github.com/adevinta/spark/assets/23620759/cd0cc8a1-141a-4625-a250-9a008a76d2e3)
![Image](https://github.com/adevinta/spark/assets/23620759/ca4adb97-e1cd-439f-b589-a308adad9637)
![Image](https://github.com/adevinta/spark/assets/23620759/aff3ffe4-d8a7-4104-be3a-b4971505bf1f)
![Image](https://github.com/adevinta/spark/assets/23620759/6ba95645-5054-4918-b6c3-6bf09bd14ed5)
![Image](https://github.com/adevinta/spark/assets/23620759/92e2e83b-773d-46b0-97b1-1038c9282f0a)

**Comment by mathieuhervouetlbc** [comment]
- [ ] that we do not have any more icons for countriy flags.
- [ ] It seems like the following icons are the same: [color](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Color.svg) vs [colors](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Colors.svg), [brand](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Brand.svg) and [model](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Model.svg), [start](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Start.svg) and [arrival](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Arrival.svg), [check](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Check.svg) and [check fill](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/CheckFill.svg)
- [ ] Is there smth to replace Energy Class icon (attached in :threadplz:) (could it be replaced by [Class](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/Class.svg)?), car brand?
- [ ] Holidays Garden icon seems to be missing, shall we replace it with Garden?
- [ ] Mailbox closed/open Up seem to be missing, can they be replaced with [Mail Open Fill](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/MailOpenFill.svg) and [Mail Close Fil](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/MailCloseFill.svg)l?
- [ ] Error photo seems to be missing (attached)
- [ ] Is there anything to replace Booster , Apparations (attached) ?
- [ ] [ProOutline](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/ProOutline.svg) does not really look outline :thinking_face:
- [ ] We no longer have avatar image (attached), can it be replaced by [profile](https://github.com/adevinta/spark-tokens/blob/main/assets/spark/icons/ProfileFill.svg)

**Comment by mathieuhervouetlbc** [comment]
@MarinaRomanova @turolopezsanabria 

- Similar icons is because we have same icons for differents verticals. So `Color` is actually `Car Color` and `Colors` is `Clothes Colors`. But I can merge them to gain space/weight.
- `Energy Class` is now `Class`
- `Holidays garden` is missing we need to add it in the repo
- `Mail Open Fill` and `Mail Close Fill` are the new `Mailbox closed/openup`
- `Error photo` are now `NoPhoto`
- I just made the `Appearance` and `Booster` icons (we need to add them in the Repo)
- We don't have `ProOutline` but Pro Square or `ProCircle` in Figma
- I just made the `Avatar` icon (we need to add it in the Repo)

**Comment by soulcramer** [comment]
@mathieuhervouetlbc For the `Error photo` we need a different one than `NoPhoto` as it is already used when there's no photo/image to get (like in ad details where there's no image) and Error Photo is used when we couldn't get or display the image (network error, server error or even the image is in a unsupported format)

<img width="125" alt="image" src="https://github.com/adevinta/spark/assets/11772084/ea03f3d7-8336-4e9d-8d50-165bff0b1c31">
