### ISSUE TITLE
[Components] - FormField - Add characters count component

### ISSUE THREAD

**Issue by andresz1** [adevinta/spark#888]
### Description

Input component should provide an easy way to display a character counter

### Problem Statement/Justification

Inputs with a maximum number of characters should optionally provide instant feedback about the number of characters

### Proposed Solution or API

```jsx
<FormField>
  <FormField.Label>My field</FormField.Label>

  <Input value={value} onValueChange={setValue} maxLength={maxLength} />

  <div className="flex gap-md justify-between">
    <div className="flex-grow">
      <FormField.HelperMessage>Helper</FormField.HelperMessage>
      <FormField.ErrorMessage>Error</FormField.ErrorMessage>
    </div>
    
    <FormField.CharactersCount value={value} maxLength={maxLength} />
  </div>
</FormField>
```

#### Props

- `value` is a required `string`
- `maxLength` is an optional `number`

**Comment by kikoruiz** [comment]
Fixed by https://github.com/adevinta/spark/pull/1033
