### ISSUE TITLE
Label color for the TextField

### ISSUE THREAD

**Issue by andresz1** [adevinta/spark#928]
### Description

Add intent color to Label component and TextField label

### Problem Statement/Justification

The TextField label doesn't have intent color

**Comment by andresz1** [comment]
https://github.com/adevinta/spark/pull/919

**Comment by soykje** [comment]
I added the "blocked" label as this work is dependent on #910

**Comment by Powerplex** [comment]
Closing as TextField will be removed to only have Input as a package :)
