### ISSUE TITLE
[Component] Slider

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark#961]

**Comment by soykje** [comment]
On the web side the design specs seems to be ready? wdyt @JeremiasUX ?

**Comment by JeremiasUX** [comment]
Yea, I would say so

**Comment by soykje** [comment]
> Yea, I would say so

It seems we only miss the `disabled` state update (from DIM4 to DIM3) and you'll have an approval on the web side :tada:

**Comment by soykje** [comment]
@elisa-hery The component is ready to test on web side, be my guest! 🙂

**Comment by soykje** [comment]
Moving back to dev stage, as there has been some changes on halo styles.

**Comment by soykje** [comment]
Hi everyone :wave: Following last design updates, here is the last version of web implementation: https://github.com/adevinta/spark/pull/1406#issuecomment-1737554821 Thx in advance for your reviews :pray:

**Comment by soykje** [comment]
@elisa-hery Last changes have been approved by team mates, so we're good for a new testing session! :tada:

**Comment by elisa-hery** [comment]
@soykje here are my comment after testing : 

1.  in responsive and on chrome only, it's almost impossible to move the "handler" (except when clicking on the track, where it does move - see video below)
2. about focus, figma says "keyboard navigation only", but on storybook you can see the focus when you click. I don't know if this is normal! --> it's a radix bug, seen with @turolopezsanabria and @JeremiasUX we can merge like this https://github.com/adevinta/spark/issues/1471  
3. track colour: on Storybook the `onBackground` is black #000000, whereas on figma it's the colour #1D1F2A --> slack thread [here](https://adevinta.slack.com/archives/C04LNCEMMUN/p1696583537959389)
4. the specs clearly state that the border-radius is customisable, shouldn't this also be written in storyBook ? --> will be updated
5. perhaps to check during design review : if you want to click on the track to move the handler, the click zone is very small (4px high) and it's not easy. I don't know if we could/would enlarge this area



https://github.com/adevinta/spark/assets/142396647/e9802694-f4b2-425e-a94e-def25ed2fd83

**Comment by elisa-hery** [comment]
@soykje thanks, thanks ! My comments : 

1. fixed ✅ !
2. ok
3. i'll talk about it with @JeremiasUX 
4. done ✅  thanks !
5. i'll talk about it with @JeremiasUX 

@JeremiasUX --> component ready for design review !

**Comment by JeremiasUX** [comment]
Design review:

- "Pressed" should not have a focus. Focus is only for keyboard navigation
- Range Slider: As soon as you move one handle above the other, the design changes of the second handle (image attached)
- Shape naming should be **Square** and **Pill** 
- "Prevent thumb overlap" is not part of the spec, is that feature necessary? 


<img width="1025" alt="Bildschirmfoto 2023-10-11 um 09 09 20" src="https://github.com/adevinta/spark/assets/139337913/1e94d316-f87f-4f60-baa3-0e839831079e">

**Comment by soykje** [comment]
1. What do you mean by "pressed" here? It seems like the same as focus, or am I missing something?
2. Not sure to get your point... Maybe we could discuss this directly?
3. N/A
4. Not necessary at all, but a suggestion as the base component from Radix UI proposes it :slightly_smiling_face: It seems to me a nice to have, but we can omit it if you prefer :+1:

**Comment by turolopezsanabria** [comment]
Hello 🙋🏻‍♂️
yes confirmed, we can move forward, just make sure we have the 2 remaining issues documented in tickets so we don't lose track of them
