### ISSUE TITLE
[Tag] Remove shape prop

### ISSUE THREAD

**Issue by soykje** [adevinta/spark#978]
As specs says, there shouldn't be more than one shape. So the prop should be removed, using only one (fully rounded).

**Comment by soykje** [comment]
@turolopezsanabria @mathieuhervouetlbc Ready to test https://spark-k8wna3atl-spark-team.vercel.app/?path=/docs/components-tag--docs#props

**Comment by turolopezsanabria** [comment]
👍🏼 lgtm
