### ISSUE TITLE
[Component] Progress-bar

### ISSUE THREAD

**Issue by soykje** [adevinta/spark#991]
Waiting for Design specs, we want to open the discussions about possible API for the Progress component ([here](https://github.com/adevinta/spark/discussions/992)) then after agreement start development in parallel with design team.

**Comment by andresz1** [comment]
- Preview: https://sparkui.vercel.app/?path=/docs/experimental-progress--docs
- Specs: https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=7229-1207&mode=design&t=PxwE4VjVC6bfL6MB-0
